[37m2022-07-16 01:23:51.588 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:23:51.590 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:23:51.590 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:23:51.590 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:23:51.591 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:23:51.591 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:23:51.852 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:23:51.855 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:23:51.856 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:24:00.833 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:24:00.834 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:24:00.834 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:24:00.834 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:24:00.835 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:24:00.835 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:24:00.950 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:24:00.951 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:24:00.952 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:27:03.468 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:27:03.469 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:27:03.469 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:27:03.469 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:27:03.470 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:27:03.470 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:27:03.609 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:27:03.610 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:27:03.610 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:27:14.974 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:27:14.974 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:27:14.975 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:27:14.975 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:27:14.976 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:27:14.976 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:27:15.69 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:27:15.69 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:27:15.70 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:27:50.473 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:27:50.474 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:27:50.474 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:27:50.475 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:27:50.476 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:27:50.477 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:27:50.559 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:27:50.560 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:27:50.560 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:30:45.700 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:30:45.701 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:30:45.701 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:30:45.701 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:30:45.703 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:30:45.703 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:30:45.985 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:30:45.986 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:30:45.987 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:31:10.867 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:31:10.868 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:31:10.868 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:31:10.868 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:31:10.869 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:31:10.869 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:31:11.74 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:31:11.76 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:31:11.76 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:31:58.283 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:31:58.284 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:31:58.284 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:31:58.284 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:31:58.285 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:31:58.286 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:31:58.467 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:31:58.469 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:31:58.469 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:35:31.744 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:35:31.745 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:35:31.745 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:35:31.746 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:35:31.746 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:35:31.747 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:35:31.921 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:35:31.922 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:35:31.922 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:36:26.245 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:36:26.246 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:36:26.246 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:36:26.246 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:36:26.247 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:36:26.248 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:36:26.417 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:36:26.418 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:36:26.418 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:37:12.748 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:37:12.749 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:37:12.749 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:37:12.750 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:37:12.750 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:37:12.750 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:37:12.995 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:37:12.997 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:37:12.997 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:37:26.491 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:37:26.492 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:37:26.492 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:37:26.493 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:37:26.493 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:37:26.494 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:37:27.29 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:37:27.31 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:37:27.32 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:39:56.981 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:39:56.982 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:39:56.982 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:39:56.982 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:39:56.983 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:39:56.984 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:39:57.153 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:39:57.155 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:39:57.155 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:42:43.495 | INFO     |  [DataReader.py:80] {'scout_id': 'pranav', 'match_key': 'qm3', 'team_number': '1719', 'alliance': 'Red', 'driver_station': '2', 'preloaded_cargo': '1', 'auto_lower_hub': '0', 'auto_upper_hub': '0', 'auto_misses': '0', 'taxied': '1', 'auto_shooting_zones': 'Tarmac', 'teleop_lower_hub': '0', 'teleop_upper_hub': '1', 'teleop_misses': '5', 'teleop_shooting_zones': 'Elsewhere', 'attempted_low': None, 'attempted_mid': '1', 'attempted_high': None, 'attempted_traversal': None, 'climb_time': '1', 'final_climb_type': 'No Climb', 'defense_pct': '0', 'defense_rating': None, 'counter_defense_pct': '0', 'counter_defense_rating': None, 'driver_rating': '3', 'auto_notes': 'notes for auto', 'teleop_notes': 'notes for teleop', 'misc_notes': 'notes for misc'}[0m
[32m2022-07-16 01:42:43.496 | DEBUG    |  [DataReader.py:82] Scanned Successfully![0m
[1;33m2022-07-16 01:42:43.880 | WARNING  |  [DataReader.py:84] Already Scanned[0m
[1;33m2022-07-16 01:42:44.27 | WARNING  |  [DataReader.py:84] Already Scanned[0m
[37m2022-07-16 01:43:24.538 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm3[0m
[37m2022-07-16 01:43:24.539 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm3[0m
[37m2022-07-16 01:43:24.539 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm3[0m
[1;31m2022-07-16 01:43:24.539 | ERROR    |  [DataVal.py:238] frc1719 was NOT IN MATCH qm3, on the Red alliance[0m
[37m2022-07-16 01:43:24.539 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm3[0m
[37m2022-07-16 01:43:24.540 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm3[0m
[37m2022-07-16 01:43:24.540 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm3[0m
[37m2022-07-16 01:43:24.540 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm3[0m
[37m2022-07-16 01:43:24.540 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm3[0m
[37m2022-07-16 01:43:24.540 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-16 01:43:24.541 | INFO     |  [DataVal.py:113] Finished SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-16 01:43:24.541 | INFO     |  [DataVal.py:115] Starting CLIMB VALIDATION qm3[0m
[37m2022-07-16 01:43:24.541 | INFO     |  [DataVal.py:117] Finished CLIMB VALIDATION qm3[0m
[37m2022-07-16 01:43:24.541 | INFO     |  [DataVal.py:119] Starting DEFENSE VALIDATION qm3[0m
[37m2022-07-16 01:43:24.541 | INFO     |  [DataVal.py:121] Finished DEFENSE VALIDATION qm3[0m
[37m2022-07-16 01:43:24.541 | INFO     |  [DataVal.py:131] Starting TBA VALIDATION qm3[0m
[1;35m2022-07-16 01:43:24.541 | CRITICAL |  [DataManager.py:38] Validation failed.[0m
[32m2022-07-16 01:43:24.541 | DEBUG    |  [DataManager.py:39] 'NoneType' object is not subscriptable[0m
[37m2022-07-16 01:43:39.513 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:43:39.514 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:43:39.514 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:43:39.514 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:43:39.515 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:43:39.516 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:43:39.722 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:43:39.724 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:43:39.724 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:43:52.105 | INFO     |  [DataReader.py:79] {'scout_id': 'pranav', 'match_key': 'qm3', 'team_number': '1719', 'alliance': 'Red', 'driver_station': '2', 'preloaded_cargo': '1', 'auto_lower_hub': '0', 'auto_upper_hub': '0', 'auto_misses': '0', 'taxied': '1', 'auto_shooting_zones': 'Tarmac', 'teleop_lower_hub': '0', 'teleop_upper_hub': '1', 'teleop_misses': '5', 'teleop_shooting_zones': 'Elsewhere', 'attempted_low': None, 'attempted_mid': '1', 'attempted_high': None, 'attempted_traversal': None, 'climb_time': '1', 'final_climb_type': 'No Climb', 'defense_pct': '0', 'defense_rating': None, 'counter_defense_pct': '0', 'counter_defense_rating': None, 'driver_rating': '3', 'auto_notes': 'notes for auto', 'teleop_notes': 'notes for teleop', 'misc_notes': 'notes for misc'}[0m
[32m2022-07-16 01:43:52.106 | DEBUG    |  [DataReader.py:81] Scanned Successfully![0m
[1;33m2022-07-16 01:43:52.307 | WARNING  |  [DataReader.py:83] Already Scanned[0m
[1;33m2022-07-16 01:43:52.442 | WARNING  |  [DataReader.py:83] Already Scanned[0m
[1;33m2022-07-16 01:43:52.565 | WARNING  |  [DataReader.py:83] Already Scanned[0m
[37m2022-07-16 01:48:38.780 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm3[0m
[37m2022-07-16 01:48:38.781 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm3[0m
[37m2022-07-16 01:48:38.781 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm3[0m
[1;31m2022-07-16 01:48:38.781 | ERROR    |  [DataVal.py:238] frc1719 was NOT IN MATCH qm3, on the Red alliance[0m
[37m2022-07-16 01:48:38.782 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm3[0m
[37m2022-07-16 01:48:38.782 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm3[0m
[37m2022-07-16 01:48:38.782 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm3[0m
[37m2022-07-16 01:48:38.782 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm3[0m
[37m2022-07-16 01:48:38.782 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm3[0m
[37m2022-07-16 01:48:38.782 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-16 01:48:38.782 | INFO     |  [DataVal.py:113] Finished SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-16 01:48:38.782 | INFO     |  [DataVal.py:115] Starting CLIMB VALIDATION qm3[0m
[37m2022-07-16 01:48:38.782 | INFO     |  [DataVal.py:117] Finished CLIMB VALIDATION qm3[0m
[37m2022-07-16 01:48:38.782 | INFO     |  [DataVal.py:119] Starting DEFENSE VALIDATION qm3[0m
[37m2022-07-16 01:48:38.782 | INFO     |  [DataVal.py:121] Finished DEFENSE VALIDATION qm3[0m
[37m2022-07-16 01:48:38.782 | INFO     |  [DataVal.py:131] Starting TBA VALIDATION qm3[0m
[1;35m2022-07-16 01:48:38.783 | CRITICAL |  [DataManager.py:38] Validation failed.[0m
[32m2022-07-16 01:48:38.783 | DEBUG    |  [DataManager.py:39] 'NoneType' object is not subscriptable[0m
[37m2022-07-16 01:49:02.100 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:49:02.100 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:49:02.100 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:49:02.100 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:49:02.101 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:49:02.101 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:49:02.245 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:49:02.247 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:49:02.247 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:49:25.228 | INFO     |  [DataReader.py:80] {'scout_id': 'pranav', 'match_key': 'qm3', 'team_number': '1719', 'alliance': 'Red', 'driver_station': '2', 'preloaded_cargo': '1', 'auto_lower_hub': '0', 'auto_upper_hub': '0', 'auto_misses': '0', 'taxied': '1', 'auto_shooting_zones': 'Tarmac', 'teleop_lower_hub': '0', 'teleop_upper_hub': '1', 'teleop_misses': '5', 'teleop_shooting_zones': 'Elsewhere', 'attempted_low': None, 'attempted_mid': '1', 'attempted_high': None, 'attempted_traversal': None, 'climb_time': '1', 'final_climb_type': 'No Climb', 'defense_pct': '0', 'defense_rating': None, 'counter_defense_pct': '0', 'counter_defense_rating': None, 'driver_rating': '3', 'auto_notes': 'notes for auto', 'teleop_notes': 'notes for teleop', 'misc_notes': 'notes for misc'}[0m
[32m2022-07-16 01:49:25.229 | DEBUG    |  [DataReader.py:84] Scanned Successfully![0m
[1;33m2022-07-16 01:49:25.633 | WARNING  |  [DataReader.py:86] Already Scanned[0m
[37m2022-07-16 01:57:15.87 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm3[0m
[37m2022-07-16 01:57:15.88 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm3[0m
[37m2022-07-16 01:57:15.88 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm3[0m
[1;31m2022-07-16 01:57:15.88 | ERROR    |  [DataVal.py:238] frc1719 was NOT IN MATCH qm3, on the Red alliance[0m
[37m2022-07-16 01:57:15.88 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm3[0m
[37m2022-07-16 01:57:15.89 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm3[0m
[37m2022-07-16 01:57:15.89 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm3[0m
[37m2022-07-16 01:57:15.89 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm3[0m
[37m2022-07-16 01:57:15.89 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm3[0m
[37m2022-07-16 01:57:15.89 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-16 01:57:15.89 | INFO     |  [DataVal.py:113] Finished SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-16 01:57:15.89 | INFO     |  [DataVal.py:115] Starting CLIMB VALIDATION qm3[0m
[37m2022-07-16 01:57:15.89 | INFO     |  [DataVal.py:117] Finished CLIMB VALIDATION qm3[0m
[37m2022-07-16 01:57:15.89 | INFO     |  [DataVal.py:119] Starting DEFENSE VALIDATION qm3[0m
[37m2022-07-16 01:57:15.89 | INFO     |  [DataVal.py:121] Finished DEFENSE VALIDATION qm3[0m
[37m2022-07-16 01:57:15.89 | INFO     |  [DataVal.py:131] Starting TBA VALIDATION qm3[0m
[1;35m2022-07-16 01:57:15.89 | CRITICAL |  [DataManager.py:38] Validation failed.[0m
[32m2022-07-16 01:57:15.90 | DEBUG    |  [DataManager.py:39] 'NoneType' object is not subscriptable[0m
[37m2022-07-16 01:57:27.81 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:57:27.81 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:57:27.81 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:57:27.82 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:57:27.83 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:57:27.84 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:57:27.298 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:57:27.301 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:57:27.301 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:57:40.822 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:57:40.822 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:57:40.822 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:57:40.822 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:57:40.823 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:57:40.823 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:57:40.903 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:57:40.904 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:57:40.904 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:57:57.990 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:57:57.990 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:57:57.991 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:57:57.991 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:57:57.991 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:57:57.991 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:57:58.143 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:57:58.144 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:57:58.145 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:58:26.76 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:58:26.76 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:58:26.76 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:58:26.77 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:58:26.77 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:58:26.77 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:58:26.238 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:58:26.239 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:58:26.239 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:58:38.876 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:58:38.877 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:58:38.877 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:58:38.877 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:58:38.878 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:58:38.878 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:58:39.53 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:58:39.55 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:58:39.55 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 01:58:43.514 | INFO     |  [DataReader.py:89] {'scout_id': 'pranav', 'match_key': 'qm3', 'team_number': '1719', 'alliance': 'Red', 'driver_station': '2', 'preloaded_cargo': '1', 'auto_lower_hub': '0', 'auto_upper_hub': '0', 'auto_misses': '0', 'taxied': '1', 'auto_shooting_zones': 'Tarmac', 'teleop_lower_hub': '0', 'teleop_upper_hub': '1', 'teleop_misses': '5', 'teleop_shooting_zones': 'Elsewhere', 'attempted_low': None, 'attempted_mid': '1', 'attempted_high': None, 'attempted_traversal': None, 'climb_time': '1', 'final_climb_type': 'No Climb', 'defense_pct': '0', 'defense_rating': None, 'counter_defense_pct': '0', 'counter_defense_rating': None, 'driver_rating': '3', 'auto_notes': 'notes for auto', 'teleop_notes': 'notes for teleop', 'misc_notes': 'notes for misc'}[0m
[32m2022-07-16 01:58:43.514 | DEBUG    |  [DataReader.py:93] Scanned Successfully![0m
[37m2022-07-16 01:59:07.117 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm3[0m
[37m2022-07-16 01:59:07.118 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm3[0m
[37m2022-07-16 01:59:07.118 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm3[0m
[1;31m2022-07-16 01:59:07.118 | ERROR    |  [DataVal.py:238] frc1719 was NOT IN MATCH qm3, on the Red alliance[0m
[37m2022-07-16 01:59:07.118 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm3[0m
[37m2022-07-16 01:59:07.118 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm3[0m
[37m2022-07-16 01:59:07.118 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm3[0m
[37m2022-07-16 01:59:07.118 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm3[0m
[37m2022-07-16 01:59:07.118 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm3[0m
[37m2022-07-16 01:59:07.118 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-16 01:59:07.118 | INFO     |  [DataVal.py:113] Finished SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-16 01:59:07.118 | INFO     |  [DataVal.py:115] Starting CLIMB VALIDATION qm3[0m
[37m2022-07-16 01:59:07.119 | INFO     |  [DataVal.py:117] Finished CLIMB VALIDATION qm3[0m
[37m2022-07-16 01:59:07.119 | INFO     |  [DataVal.py:119] Starting DEFENSE VALIDATION qm3[0m
[37m2022-07-16 01:59:07.119 | INFO     |  [DataVal.py:121] Finished DEFENSE VALIDATION qm3[0m
[37m2022-07-16 01:59:07.119 | INFO     |  [DataVal.py:131] Starting TBA VALIDATION qm3[0m
[1;35m2022-07-16 01:59:07.119 | CRITICAL |  [DataManager.py:38] Validation failed.[0m
[32m2022-07-16 01:59:07.119 | DEBUG    |  [DataManager.py:39] 'NoneType' object is not subscriptable[0m
[37m2022-07-16 01:59:13.258 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 01:59:13.258 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 01:59:13.259 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 01:59:13.259 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 01:59:13.259 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 01:59:13.259 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 01:59:13.345 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 01:59:13.346 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 01:59:13.346 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:00:15.730 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:00:15.731 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:00:15.731 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:00:15.731 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:00:15.732 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:00:15.732 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:00:15.882 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:00:15.883 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:00:15.884 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:02:10.368 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:02:10.368 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:02:10.369 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:02:10.369 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:02:10.370 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:02:10.370 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:02:10.547 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:02:10.549 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:02:10.550 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:02:34.547 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:02:34.547 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:02:34.547 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:02:34.548 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:02:34.549 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:02:34.549 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:02:34.673 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:02:34.674 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:02:34.674 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:03:06.426 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:03:06.426 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:03:06.427 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:03:06.427 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:03:06.427 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:03:06.428 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:03:06.590 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:03:06.592 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:03:06.592 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:04:03.534 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:04:03.534 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:04:03.535 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:04:03.535 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:04:03.537 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:04:03.537 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:04:04.742 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:04:04.744 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:04:04.745 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:04:36.252 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:04:36.252 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:04:36.252 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:04:36.252 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:04:36.253 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:04:36.254 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:04:36.490 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:04:36.493 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:04:36.493 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:05:04.230 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:05:04.231 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:05:04.231 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:05:04.231 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:05:04.232 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:05:04.232 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:05:04.357 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:05:04.358 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:05:04.358 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:05:31.760 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:05:31.760 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:05:31.761 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:05:31.761 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:05:31.761 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:05:31.761 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:05:31.874 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:05:31.874 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:05:31.875 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:05:55.145 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:05:55.145 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:05:55.146 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:05:55.146 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:05:55.146 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:05:55.147 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:05:55.231 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:05:55.233 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:05:55.233 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:06:57.432 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:06:57.432 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:06:57.432 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:06:57.433 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:06:57.434 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:06:57.434 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:06:57.651 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:06:57.652 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:06:57.653 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:07:13.568 | INFO     |  [DataReader.py:92] {'scout_id': 'pranav', 'match_key': 'qm3', 'team_number': '1719', 'alliance': 'Red', 'driver_station': '2', 'preloaded_cargo': '1', 'auto_lower_hub': '0', 'auto_upper_hub': '0', 'auto_misses': '0', 'taxied': '1', 'auto_shooting_zones': 'Tarmac', 'teleop_lower_hub': '0', 'teleop_upper_hub': '1', 'teleop_misses': '5', 'teleop_shooting_zones': 'Elsewhere', 'attempted_low': None, 'attempted_mid': '1', 'attempted_high': None, 'attempted_traversal': None, 'climb_time': '1', 'final_climb_type': 'No Climb', 'defense_pct': '0', 'defense_rating': None, 'counter_defense_pct': '0', 'counter_defense_rating': None, 'driver_rating': '3', 'auto_notes': 'notes for auto', 'teleop_notes': 'notes for teleop', 'misc_notes': 'notes for misc'}[0m
[32m2022-07-16 02:07:13.569 | DEBUG    |  [DataReader.py:96] Scanned Successfully![0m
[37m2022-07-16 02:09:11.671 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm3[0m
[37m2022-07-16 02:09:11.671 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm3[0m
[37m2022-07-16 02:09:11.672 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm3[0m
[1;31m2022-07-16 02:09:11.672 | ERROR    |  [DataVal.py:238] frc1719 was NOT IN MATCH qm3, on the Red alliance[0m
[37m2022-07-16 02:09:11.672 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm3[0m
[37m2022-07-16 02:09:11.672 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm3[0m
[37m2022-07-16 02:09:11.672 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm3[0m
[37m2022-07-16 02:09:11.672 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm3[0m
[37m2022-07-16 02:09:11.672 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm3[0m
[37m2022-07-16 02:09:11.672 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-16 02:09:11.672 | INFO     |  [DataVal.py:113] Finished SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-16 02:09:11.673 | INFO     |  [DataVal.py:115] Starting CLIMB VALIDATION qm3[0m
[37m2022-07-16 02:09:11.673 | INFO     |  [DataVal.py:117] Finished CLIMB VALIDATION qm3[0m
[37m2022-07-16 02:09:11.673 | INFO     |  [DataVal.py:119] Starting DEFENSE VALIDATION qm3[0m
[37m2022-07-16 02:09:11.673 | INFO     |  [DataVal.py:121] Finished DEFENSE VALIDATION qm3[0m
[37m2022-07-16 02:09:11.673 | INFO     |  [DataVal.py:131] Starting TBA VALIDATION qm3[0m
[1;35m2022-07-16 02:09:11.673 | CRITICAL |  [DataManager.py:38] Validation failed.[0m
[32m2022-07-16 02:09:11.673 | DEBUG    |  [DataManager.py:39] 'NoneType' object is not subscriptable[0m
[37m2022-07-16 02:09:16.115 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:09:16.116 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:09:16.116 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:09:16.116 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:09:16.118 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:09:16.118 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:09:16.291 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:09:16.293 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:09:16.293 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:10:26.243 | INFO     |  [DataReader.py:92] {'scout_id': 'matthew', 'match_key': 'qm10', 'team_number': '4099', 'alliance': 'Red', 'driver_station': '1', 'preloaded_cargo': '0', 'auto_lower_hub': '0', 'auto_upper_hub': '0', 'auto_misses': '0', 'taxied': '0', 'auto_shooting_zones': None, 'teleop_lower_hub': '0', 'teleop_upper_hub': '0', 'teleop_misses': '0', 'teleop_shooting_zones': None, 'attempted_low': None, 'attempted_mid': None, 'attempted_high': None, 'attempted_traversal': None, 'climb_time': None, 'final_climb_type': None, 'defense_pct': '0', 'defense_rating': None, 'counter_defense_pct': '0', 'counter_defense_rating': None, 'driver_rating': '3', 'auto_notes': None, 'teleop_notes': None, 'misc_notes': None}[0m
[32m2022-07-16 02:10:26.243 | DEBUG    |  [DataReader.py:96] Scanned Successfully![0m
[1;33m2022-07-16 02:10:26.378 | WARNING  |  [DataReader.py:98] Already Scanned[0m
[1;33m2022-07-16 02:10:26.577 | WARNING  |  [DataReader.py:98] Already Scanned[0m
[1;33m2022-07-16 02:10:26.711 | WARNING  |  [DataReader.py:98] Already Scanned[0m
[37m2022-07-16 02:10:28.980 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:10:28.981 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:10:28.981 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm10[0m
[1;31m2022-07-16 02:10:28.981 | ERROR    |  [DataVal.py:238] frc4099 was NOT IN MATCH qm10, on the Red alliance[0m
[37m2022-07-16 02:10:28.981 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm10[0m
[37m2022-07-16 02:10:28.981 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:10:28.981 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:10:28.981 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:10:28.981 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:10:28.981 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:10:28.981 | INFO     |  [DataVal.py:113] Finished SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:10:28.981 | INFO     |  [DataVal.py:115] Starting CLIMB VALIDATION qm10[0m
[37m2022-07-16 02:10:28.981 | INFO     |  [DataVal.py:117] Finished CLIMB VALIDATION qm10[0m
[37m2022-07-16 02:10:28.981 | INFO     |  [DataVal.py:119] Starting DEFENSE VALIDATION qm10[0m
[37m2022-07-16 02:10:28.982 | INFO     |  [DataVal.py:121] Finished DEFENSE VALIDATION qm10[0m
[37m2022-07-16 02:10:28.982 | INFO     |  [DataVal.py:131] Starting TBA VALIDATION qm10[0m
[1;35m2022-07-16 02:10:28.982 | CRITICAL |  [DataManager.py:38] Validation failed.[0m
[32m2022-07-16 02:10:28.982 | DEBUG    |  [DataManager.py:39] 'NoneType' object is not subscriptable[0m
[37m2022-07-16 02:10:34.66 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:10:34.67 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:10:34.68 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:10:34.68 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:10:34.68 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:10:34.69 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:10:34.505 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:10:34.507 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:10:34.508 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:17:21.809 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:17:21.811 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:17:21.811 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:17:21.811 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:17:21.812 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:17:21.812 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:17:22.2 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:17:22.3 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:17:22.4 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:17:53.958 | INFO     |  [DataReader.py:92] {'scout_id': 'matthew', 'match_key': 'qm10', 'team_number': '4099', 'alliance': 'Red', 'driver_station': '1', 'preloaded_cargo': '0', 'auto_lower_hub': '0', 'auto_upper_hub': '0', 'auto_misses': '0', 'taxied': '0', 'auto_shooting_zones': None, 'teleop_lower_hub': '0', 'teleop_upper_hub': '0', 'teleop_misses': '0', 'teleop_shooting_zones': None, 'attempted_low': None, 'attempted_mid': None, 'attempted_high': None, 'attempted_traversal': None, 'climb_time': None, 'final_climb_type': None, 'defense_pct': '0', 'defense_rating': None, 'counter_defense_pct': '0', 'counter_defense_rating': None, 'driver_rating': '3', 'auto_notes': None, 'teleop_notes': None, 'misc_notes': None}[0m
[32m2022-07-16 02:17:53.958 | DEBUG    |  [DataReader.py:96] Scanned Successfully![0m
[1;33m2022-07-16 02:17:54.420 | WARNING  |  [DataReader.py:98] Already Scanned[0m
[37m2022-07-16 02:22:21.246 | INFO     |  [DataReader.py:92] {'scout_id': 'pranav', 'match_key': 'qm10', 'team_number': '4099', 'alliance': 'Red', 'driver_station': '2', 'preloaded_cargo': '0', 'auto_lower_hub': '0', 'auto_upper_hub': '0', 'auto_misses': '0', 'taxied': '0', 'auto_shooting_zones': None, 'teleop_lower_hub': '0', 'teleop_upper_hub': '0', 'teleop_misses': '0', 'teleop_shooting_zones': None, 'attempted_low': None, 'attempted_mid': None, 'attempted_high': None, 'attempted_traversal': None, 'climb_time': None, 'final_climb_type': None, 'defense_pct': '0', 'defense_rating': None, 'counter_defense_pct': '0', 'counter_defense_rating': None, 'driver_rating': '3', 'auto_notes': None, 'teleop_notes': None, 'misc_notes': None}[0m
[32m2022-07-16 02:22:21.247 | DEBUG    |  [DataReader.py:96] Scanned Successfully![0m
[1;33m2022-07-16 02:22:21.403 | WARNING  |  [DataReader.py:98] Already Scanned[0m
[37m2022-07-16 02:23:00.32 | INFO     |  [DataReader.py:92] {'scout_id': 'sanjay', 'match_key': 'qm10', 'team_number': '4099', 'alliance': 'Blue', 'driver_station': '2', 'preloaded_cargo': '0', 'auto_lower_hub': '0', 'auto_upper_hub': '0', 'auto_misses': '0', 'taxied': '0', 'auto_shooting_zones': None, 'teleop_lower_hub': '0', 'teleop_upper_hub': '0', 'teleop_misses': '0', 'teleop_shooting_zones': None, 'attempted_low': None, 'attempted_mid': None, 'attempted_high': None, 'attempted_traversal': None, 'climb_time': None, 'final_climb_type': None, 'defense_pct': '0', 'defense_rating': None, 'counter_defense_pct': '0', 'counter_defense_rating': None, 'driver_rating': '3', 'auto_notes': None, 'teleop_notes': None, 'misc_notes': None}[0m
[32m2022-07-16 02:23:00.32 | DEBUG    |  [DataReader.py:96] Scanned Successfully![0m
[1;33m2022-07-16 02:23:00.639 | WARNING  |  [DataReader.py:98] Already Scanned[0m
[37m2022-07-16 02:23:45.140 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:23:45.141 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:23:45.141 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm10[0m
[1;31m2022-07-16 02:23:45.141 | ERROR    |  [DataVal.py:238] frc4099 was NOT IN MATCH qm10, on the Red alliance[0m
[37m2022-07-16 02:23:45.141 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.141 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.141 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.141 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:23:45.141 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:23:45.142 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.142 | INFO     |  [DataVal.py:113] Finished SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.142 | INFO     |  [DataVal.py:115] Starting CLIMB VALIDATION qm10[0m
[37m2022-07-16 02:23:45.142 | INFO     |  [DataVal.py:117] Finished CLIMB VALIDATION qm10[0m
[37m2022-07-16 02:23:45.142 | INFO     |  [DataVal.py:119] Starting DEFENSE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.143 | INFO     |  [DataVal.py:121] Finished DEFENSE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.143 | INFO     |  [DataVal.py:131] Starting TBA VALIDATION qm10[0m
[1;35m2022-07-16 02:23:45.143 | CRITICAL |  [DataManager.py:38] Validation failed.[0m
[32m2022-07-16 02:23:45.143 | DEBUG    |  [DataManager.py:39] 'NoneType' object is not subscriptable[0m
[37m2022-07-16 02:23:45.143 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:23:45.143 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:23:45.143 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm10[0m
[1;31m2022-07-16 02:23:45.144 | ERROR    |  [DataVal.py:238] frc4099 was NOT IN MATCH qm10, on the Red alliance[0m
[37m2022-07-16 02:23:45.144 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.144 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.144 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.144 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:23:45.144 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:23:45.144 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.144 | INFO     |  [DataVal.py:113] Finished SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.144 | INFO     |  [DataVal.py:115] Starting CLIMB VALIDATION qm10[0m
[37m2022-07-16 02:23:45.144 | INFO     |  [DataVal.py:117] Finished CLIMB VALIDATION qm10[0m
[37m2022-07-16 02:23:45.144 | INFO     |  [DataVal.py:119] Starting DEFENSE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.144 | INFO     |  [DataVal.py:121] Finished DEFENSE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.144 | INFO     |  [DataVal.py:131] Starting TBA VALIDATION qm10[0m
[1;35m2022-07-16 02:23:45.144 | CRITICAL |  [DataManager.py:38] Validation failed.[0m
[32m2022-07-16 02:23:45.145 | DEBUG    |  [DataManager.py:39] 'NoneType' object is not subscriptable[0m
[37m2022-07-16 02:23:45.145 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:23:45.145 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:23:45.145 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm10[0m
[1;31m2022-07-16 02:23:45.145 | ERROR    |  [DataVal.py:238] frc4099 was NOT IN MATCH qm10, on the Blue alliance[0m
[37m2022-07-16 02:23:45.145 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.145 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.145 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.145 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:23:45.145 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:23:45.145 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.145 | INFO     |  [DataVal.py:113] Finished SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.146 | INFO     |  [DataVal.py:115] Starting CLIMB VALIDATION qm10[0m
[37m2022-07-16 02:23:45.146 | INFO     |  [DataVal.py:117] Finished CLIMB VALIDATION qm10[0m
[37m2022-07-16 02:23:45.146 | INFO     |  [DataVal.py:119] Starting DEFENSE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.146 | INFO     |  [DataVal.py:121] Finished DEFENSE VALIDATION qm10[0m
[37m2022-07-16 02:23:45.146 | INFO     |  [DataVal.py:131] Starting TBA VALIDATION qm10[0m
[1;35m2022-07-16 02:23:45.146 | CRITICAL |  [DataManager.py:38] Validation failed.[0m
[32m2022-07-16 02:23:45.146 | DEBUG    |  [DataManager.py:39] 'NoneType' object is not subscriptable[0m
[37m2022-07-16 02:24:16.328 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:24:16.328 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[1;33m2022-07-16 02:24:16.328 | WARNING  |  [DataVal.py:27] Wifi Connection was not found. Will not check against TBA[0m
[37m2022-07-16 02:24:16.329 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:24:16.329 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:24:16.330 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:24:16.330 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:24:31.377 | INFO     |  [DataReader.py:92] {'scout_id': 'sanjay', 'match_key': 'qm10', 'team_number': '4099', 'alliance': 'Blue', 'driver_station': '2', 'preloaded_cargo': '0', 'auto_lower_hub': '0', 'auto_upper_hub': '0', 'auto_misses': '0', 'taxied': '0', 'auto_shooting_zones': None, 'teleop_lower_hub': '0', 'teleop_upper_hub': '0', 'teleop_misses': '0', 'teleop_shooting_zones': None, 'attempted_low': None, 'attempted_mid': None, 'attempted_high': None, 'attempted_traversal': None, 'climb_time': None, 'final_climb_type': None, 'defense_pct': '0', 'defense_rating': None, 'counter_defense_pct': '0', 'counter_defense_rating': None, 'driver_rating': '3', 'auto_notes': None, 'teleop_notes': None, 'misc_notes': None}[0m
[32m2022-07-16 02:24:31.378 | DEBUG    |  [DataReader.py:96] Scanned Successfully![0m
[1;33m2022-07-16 02:24:31.702 | WARNING  |  [DataReader.py:98] Already Scanned[0m
[37m2022-07-16 02:24:38.638 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:24:38.638 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:24:38.638 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm10[0m
[1;31m2022-07-16 02:24:38.639 | ERROR    |  [DataVal.py:238] frc4099 was NOT IN MATCH qm10, on the Blue alliance[0m
[37m2022-07-16 02:24:38.639 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm10[0m
[37m2022-07-16 02:24:38.639 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:24:38.639 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:24:38.639 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:24:38.639 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:24:38.639 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:24:38.640 | INFO     |  [DataVal.py:113] Finished SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:24:38.640 | INFO     |  [DataVal.py:115] Starting CLIMB VALIDATION qm10[0m
[37m2022-07-16 02:24:38.640 | INFO     |  [DataVal.py:117] Finished CLIMB VALIDATION qm10[0m
[37m2022-07-16 02:24:38.640 | INFO     |  [DataVal.py:119] Starting DEFENSE VALIDATION qm10[0m
[37m2022-07-16 02:24:38.640 | INFO     |  [DataVal.py:121] Finished DEFENSE VALIDATION qm10[0m
[37m2022-07-16 02:24:38.640 | INFO     |  [DataManager.py:36] Validation succeeded for submission![0m
[37m2022-07-16 02:42:02.713 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:42:02.715 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:42:02.715 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:42:02.715 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:42:02.716 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:42:02.716 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:42:02.904 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:42:02.906 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:42:02.906 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:42:07.816 | INFO     |  [DataReader.py:92] {'scout_id': 'sanjay', 'match_key': 'qm10', 'team_number': '4099', 'alliance': 'Blue', 'driver_station': '2', 'preloaded_cargo': '1', 'auto_lower_hub': '2', 'auto_upper_hub': '2', 'auto_misses': '2', 'taxied': '1', 'auto_shooting_zones': 'Fender;Opposing Fender;Elsewhere', 'teleop_lower_hub': '3', 'teleop_upper_hub': '1', 'teleop_misses': '1', 'teleop_shooting_zones': 'Opposing Tarmac;Elsewhere', 'attempted_low': '1', 'attempted_mid': '1', 'attempted_high': None, 'attempted_traversal': None, 'climb_time': '12', 'final_climb_type': 'High', 'defense_pct': '.75', 'defense_rating': '3', 'counter_defense_pct': '.5', 'counter_defense_rating': '3', 'driver_rating': '4', 'auto_notes': None, 'teleop_notes': None, 'misc_notes': None}[0m
[32m2022-07-16 02:42:07.817 | DEBUG    |  [DataReader.py:96] Scanned Successfully![0m
[1;33m2022-07-16 02:42:08.19 | WARNING  |  [DataReader.py:98] Already Scanned[0m
[37m2022-07-16 02:42:11.215 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:42:11.215 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:42:11.216 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm10[0m
[1;31m2022-07-16 02:42:11.216 | ERROR    |  [DataVal.py:238] frc4099 was NOT IN MATCH qm10, on the Blue alliance[0m
[37m2022-07-16 02:42:11.216 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm10[0m
[37m2022-07-16 02:42:11.216 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:42:11.216 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:42:11.216 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:42:11.216 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:42:11.216 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:42:11.216 | INFO     |  [DataVal.py:113] Finished SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:42:11.216 | INFO     |  [DataVal.py:115] Starting CLIMB VALIDATION qm10[0m
[1;31m2022-07-16 02:42:11.217 | ERROR    |  [DataVal.py:282] In qm10, 4099 MISSING ATTEMPTED HIGH[0m
[37m2022-07-16 02:42:11.217 | INFO     |  [DataVal.py:117] Finished CLIMB VALIDATION qm10[0m
[37m2022-07-16 02:42:11.217 | INFO     |  [DataVal.py:119] Starting DEFENSE VALIDATION qm10[0m
[1;31m2022-07-16 02:42:11.217 | ERROR    |  [DataVal.py:330] In qm10, 4099 DEFENSE AND COUNTER DEFENSE PCT TOO HIGH[0m
[37m2022-07-16 02:42:11.217 | INFO     |  [DataVal.py:121] Finished DEFENSE VALIDATION qm10[0m
[37m2022-07-16 02:42:11.217 | INFO     |  [DataVal.py:131] Starting TBA VALIDATION qm10[0m
[1;35m2022-07-16 02:42:11.217 | CRITICAL |  [DataManager.py:38] Validation failed.[0m
[32m2022-07-16 02:42:11.217 | DEBUG    |  [DataManager.py:39] 'NoneType' object is not subscriptable[0m
[37m2022-07-16 02:42:59.229 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:42:59.230 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:42:59.230 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:42:59.231 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:42:59.232 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:42:59.232 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:42:59.419 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:42:59.421 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:42:59.422 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:43:25.501 | INFO     |  [DataReader.py:92] {'scout_id': 'sanjay', 'match_key': 'qm10', 'team_number': '4099', 'alliance': 'Blue', 'driver_station': '2', 'preloaded_cargo': '1', 'auto_lower_hub': '2', 'auto_upper_hub': '2', 'auto_misses': '2', 'taxied': '1', 'auto_shooting_zones': 'Fender;Opposing Fender;Elsewhere', 'teleop_lower_hub': '3', 'teleop_upper_hub': '1', 'teleop_misses': '1', 'teleop_shooting_zones': 'Opposing Tarmac;Elsewhere', 'attempted_low': '1', 'attempted_mid': '1', 'attempted_high': None, 'attempted_traversal': None, 'climb_time': '12', 'final_climb_type': 'High', 'defense_pct': '.75', 'defense_rating': '3', 'counter_defense_pct': '.5', 'counter_defense_rating': '3', 'driver_rating': '4', 'auto_notes': None, 'teleop_notes': None, 'misc_notes': None}[0m
[32m2022-07-16 02:43:25.501 | DEBUG    |  [DataReader.py:96] Scanned Successfully![0m
[1;33m2022-07-16 02:43:25.704 | WARNING  |  [DataReader.py:98] Already Scanned[0m
[37m2022-07-16 02:43:29.547 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:43:29.547 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:43:29.547 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm10[0m
[1;31m2022-07-16 02:43:29.547 | ERROR    |  [DataVal.py:238] frc4099 was NOT IN MATCH qm10, on the Blue alliance[0m
[37m2022-07-16 02:43:29.547 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm10[0m
[37m2022-07-16 02:43:29.548 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:43:29.548 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:43:29.548 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:43:29.548 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:43:29.548 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:43:29.548 | INFO     |  [DataVal.py:113] Finished SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:43:29.548 | INFO     |  [DataVal.py:115] Starting CLIMB VALIDATION qm10[0m
[1;31m2022-07-16 02:43:29.548 | ERROR    |  [DataVal.py:282] In qm10, 4099 MISSING ATTEMPTED HIGH[0m
[37m2022-07-16 02:43:29.548 | INFO     |  [DataVal.py:117] Finished CLIMB VALIDATION qm10[0m
[37m2022-07-16 02:43:29.548 | INFO     |  [DataVal.py:119] Starting DEFENSE VALIDATION qm10[0m
[1;31m2022-07-16 02:43:29.548 | ERROR    |  [DataVal.py:330] In qm10, 4099 DEFENSE AND COUNTER DEFENSE PCT TOO HIGH[0m
[37m2022-07-16 02:43:29.548 | INFO     |  [DataVal.py:121] Finished DEFENSE VALIDATION qm10[0m
[37m2022-07-16 02:43:29.548 | INFO     |  [DataVal.py:131] Starting TBA VALIDATION qm10[0m
[1;35m2022-07-16 02:43:29.549 | CRITICAL |  [DataManager.py:39] Validation failed.[0m
[32m2022-07-16 02:43:29.549 | DEBUG    |  [DataManager.py:40] 'NoneType' object is not subscriptable[0m
[37m2022-07-16 02:43:56.527 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:43:56.527 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:43:56.527 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:43:56.527 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:43:56.528 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:43:56.529 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:43:56.657 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:43:56.659 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:43:56.659 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:43:57.813 | INFO     |  [DataReader.py:92] {'scout_id': 'sanjay', 'match_key': 'qm10', 'team_number': '4099', 'alliance': 'Blue', 'driver_station': '2', 'preloaded_cargo': '1', 'auto_lower_hub': '2', 'auto_upper_hub': '2', 'auto_misses': '2', 'taxied': '1', 'auto_shooting_zones': 'Fender;Opposing Fender;Elsewhere', 'teleop_lower_hub': '3', 'teleop_upper_hub': '1', 'teleop_misses': '1', 'teleop_shooting_zones': 'Opposing Tarmac;Elsewhere', 'attempted_low': '1', 'attempted_mid': '1', 'attempted_high': None, 'attempted_traversal': None, 'climb_time': '12', 'final_climb_type': 'High', 'defense_pct': '.75', 'defense_rating': '3', 'counter_defense_pct': '.5', 'counter_defense_rating': '3', 'driver_rating': '4', 'auto_notes': None, 'teleop_notes': None, 'misc_notes': None}[0m
[32m2022-07-16 02:43:57.813 | DEBUG    |  [DataReader.py:96] Scanned Successfully![0m
[1;33m2022-07-16 02:43:58.380 | WARNING  |  [DataReader.py:98] Already Scanned[0m
[37m2022-07-16 02:44:02.37 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:44:02.38 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:44:02.38 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm10[0m
[1;31m2022-07-16 02:44:02.38 | ERROR    |  [DataVal.py:238] frc4099 was NOT IN MATCH qm10, on the Blue alliance[0m
[37m2022-07-16 02:44:02.38 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm10[0m
[37m2022-07-16 02:44:02.38 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:44:02.38 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:44:02.38 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:44:02.38 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:44:02.38 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:44:02.38 | INFO     |  [DataVal.py:113] Finished SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:44:02.38 | INFO     |  [DataVal.py:115] Starting CLIMB VALIDATION qm10[0m
[1;31m2022-07-16 02:44:02.39 | ERROR    |  [DataVal.py:282] In qm10, 4099 MISSING ATTEMPTED HIGH[0m
[37m2022-07-16 02:44:02.39 | INFO     |  [DataVal.py:117] Finished CLIMB VALIDATION qm10[0m
[37m2022-07-16 02:44:02.39 | INFO     |  [DataVal.py:119] Starting DEFENSE VALIDATION qm10[0m
[1;31m2022-07-16 02:44:02.39 | ERROR    |  [DataVal.py:330] In qm10, 4099 DEFENSE AND COUNTER DEFENSE PCT TOO HIGH[0m
[37m2022-07-16 02:44:02.39 | INFO     |  [DataVal.py:121] Finished DEFENSE VALIDATION qm10[0m
[37m2022-07-16 02:44:02.39 | INFO     |  [DataVal.py:131] Starting TBA VALIDATION qm10[0m
[37m2022-07-16 02:47:02.744 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:47:02.745 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:47:02.745 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:47:02.745 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:47:02.746 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:47:02.747 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:47:02.921 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:47:02.922 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:47:02.922 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:47:11.826 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-16 02:47:11.826 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-16 02:47:11.827 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-16 02:47:11.827 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-16 02:47:11.828 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-16 02:47:11.828 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-16 02:47:11.948 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-16 02:47:11.949 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-16 02:47:11.949 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-16 02:47:21.27 | INFO     |  [DataReader.py:92] {'scout_id': 'sanjay', 'match_key': 'qm10', 'team_number': '4099', 'alliance': 'Blue', 'driver_station': '2', 'preloaded_cargo': '1', 'auto_lower_hub': '2', 'auto_upper_hub': '2', 'auto_misses': '2', 'taxied': '1', 'auto_shooting_zones': 'Fender;Opposing Fender;Elsewhere', 'teleop_lower_hub': '3', 'teleop_upper_hub': '1', 'teleop_misses': '1', 'teleop_shooting_zones': 'Opposing Tarmac;Elsewhere', 'attempted_low': '1', 'attempted_mid': '1', 'attempted_high': None, 'attempted_traversal': None, 'climb_time': '12', 'final_climb_type': 'High', 'defense_pct': '.75', 'defense_rating': '3', 'counter_defense_pct': '.5', 'counter_defense_rating': '3', 'driver_rating': '4', 'auto_notes': None, 'teleop_notes': None, 'misc_notes': None}[0m
[32m2022-07-16 02:47:21.27 | DEBUG    |  [DataReader.py:96] Scanned Successfully![0m
[37m2022-07-16 02:47:22.921 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:47:22.921 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm10[0m
[37m2022-07-16 02:47:22.922 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm10[0m
[1;31m2022-07-16 02:47:22.922 | ERROR    |  [DataVal.py:238] frc4099 was NOT IN MATCH qm10, on the Blue alliance[0m
[37m2022-07-16 02:47:22.922 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm10[0m
[37m2022-07-16 02:47:22.922 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:47:22.922 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm10[0m
[37m2022-07-16 02:47:22.922 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:47:22.922 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm10[0m
[37m2022-07-16 02:47:22.922 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:47:22.922 | INFO     |  [DataVal.py:113] Finished SHOOTING ZONE VALIDATION qm10[0m
[37m2022-07-16 02:47:22.922 | INFO     |  [DataVal.py:115] Starting CLIMB VALIDATION qm10[0m
[1;31m2022-07-16 02:47:22.922 | ERROR    |  [DataVal.py:282] In qm10, 4099 MISSING ATTEMPTED HIGH[0m
[37m2022-07-16 02:47:22.922 | INFO     |  [DataVal.py:117] Finished CLIMB VALIDATION qm10[0m
[37m2022-07-16 02:47:22.922 | INFO     |  [DataVal.py:119] Starting DEFENSE VALIDATION qm10[0m
[1;31m2022-07-16 02:47:22.923 | ERROR    |  [DataVal.py:330] In qm10, 4099 DEFENSE AND COUNTER DEFENSE PCT TOO HIGH[0m
[37m2022-07-16 02:47:22.923 | INFO     |  [DataVal.py:121] Finished DEFENSE VALIDATION qm10[0m
[37m2022-07-16 02:47:22.923 | INFO     |  [DataVal.py:131] Starting TBA VALIDATION qm10[0m
[37m2022-07-16 02:47:22.923 | INFO     |  [DataVal.py:133] Starting TBA VALIDATION qm10[0m
[37m2022-07-16 02:47:22.923 | INFO     |  [DataManager.py:36] Validation succeeded for submission![0m
