[37m2022-07-08 12:48:26.297 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 12:48:26.297 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 12:48:26.297 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 12:48:26.298 | INFO     |  [DataVal.py:562] Getting configuration variables from config.json[0m
[37m2022-07-08 12:48:26.298 | INFO     |  [DataVal.py:575] Successfully retreived configuration variablees.[0m
[37m2022-07-08 12:48:26.949 | INFO     |  [DataVal.py:603] Writing to match_schedule json.[0m
[37m2022-07-08 12:48:26.953 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 12:48:26.953 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 12:48:26.953 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 12:48:27.460 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 12:48:27.467 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 12:48:27.468 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 12:51:27.930 | INFO     |  [DataReader.py:75] {'scout_id': 'pranav', 'match_key': 'qm3', 'team_number': 1719, 'alliance': 'Red', 'driver_station': 2, 'preloaded_cargo': 1, 'auto_lower_hub': 0, 'auto_upper_hub': 0, 'auto_misses': 0, 'taxied': 1, 'auto_shooting_zones': 'Tarmac', 'teleop_lower_hub': 0, 'teleop_upper_hub': 1, 'teleop_misses': 5, 'teleop_shooting_zones': 'Elsewhere', 'attempted_low': None, 'attempted_mid': 1, 'attempted_high': None, 'attempted_traversal': None, 'climb_time': 1, 'final_climb_type': 'No Climb', 'defense_pct': 0, 'defense_rating': None, 'counter_defense_pct': 0, 'counter_defense_rating': None, 'driver_rating': None, 'auto_notes': 'notes for auto', 'teleop_notes': 'notes for teleop', 'misc_notes': 'notes for misc'}[0m
[32m2022-07-08 12:51:27.931 | DEBUG    |  [DataReader.py:77] Scanned Successfully![0m
[1;33m2022-07-08 12:51:28.318 | WARNING  |  [DataReader.py:79] Already Scanned[0m
[1;33m2022-07-08 12:51:29.354 | WARNING  |  [DataReader.py:79] Already Scanned[0m
[37m2022-07-08 12:51:35.216 | INFO     |  [DataReader.py:75] {'scout_id': 'paolo', 'match_key': 'qm3', 'team_number': 1908, 'alliance': 'Blue', 'driver_station': 1, 'preloaded_cargo': 1, 'auto_lower_hub': 0, 'auto_upper_hub': 0, 'auto_misses': 0, 'taxied': 1, 'auto_shooting_zones': 'Tarmac', 'teleop_lower_hub': 1, 'teleop_upper_hub': 2, 'teleop_misses': 0, 'teleop_shooting_zones': 'Fender;Opposing Tarmac', 'attempted_low': 0, 'attempted_mid': 1, 'attempted_high': 0, 'attempted_traversal': 0, 'climb_time': 1, 'final_climb_type': 'Mid', 'defense_pct': 0, 'defense_rating': None, 'counter_defense_pct': 0, 'counter_defense_rating': None, 'driver_rating': None, 'auto_notes': 'notes for auto', 'teleop_notes': 'notes for teleop', 'misc_notes': 'notes for misc'}[0m
[32m2022-07-08 12:51:35.216 | DEBUG    |  [DataReader.py:77] Scanned Successfully![0m
[1;33m2022-07-08 12:51:35.417 | WARNING  |  [DataReader.py:79] Already Scanned[0m
[37m2022-07-08 12:51:37.646 | INFO     |  [DataReader.py:75] {'scout_id': 'Samuel', 'match_key': 'qm3', 'team_number': 3939, 'alliance': 'Red', 'driver_station': 1, 'preloaded_cargo': 1, 'auto_lower_hub': 0, 'auto_upper_hub': 0, 'auto_misses': 0, 'taxied': None, 'auto_shooting_zones': None, 'teleop_lower_hub': 0, 'teleop_upper_hub': 1, 'teleop_misses': 3, 'teleop_shooting_zones': 'Tarmac;Launchpad;Terminal', 'attempted_low': 1, 'attempted_mid': None, 'attempted_high': None, 'attempted_traversal': None, 'climb_time': None, 'final_climb_type': 'No Climb', 'defense_pct': 0, 'defense_rating': None, 'counter_defense_pct': 0, 'counter_defense_rating': 3, 'driver_rating': 3, 'auto_notes': 'notes for auto', 'teleop_notes': 'notes for teleop', 'misc_notes': 'notes for misc'}[0m
[32m2022-07-08 12:51:37.646 | DEBUG    |  [DataReader.py:77] Scanned Successfully![0m
[1;33m2022-07-08 12:51:37.784 | WARNING  |  [DataReader.py:79] Already Scanned[0m
[1;33m2022-07-08 12:51:38.119 | WARNING  |  [DataReader.py:79] Already Scanned[0m
[37m2022-07-08 12:51:39.113 | INFO     |  [DataReader.py:75] {'scout_id': 'anil', 'match_key': 'qm3', 'team_number': 2186, 'alliance': 'Blue', 'driver_station': 3, 'preloaded_cargo': 1, 'auto_lower_hub': 0, 'auto_upper_hub': 1, 'auto_misses': 0, 'taxied': 1, 'auto_shooting_zones': 'Tarmac', 'teleop_lower_hub': 0, 'teleop_upper_hub': 0, 'teleop_misses': 0, 'teleop_shooting_zones': None, 'attempted_low': 0, 'attempted_mid': 0, 'attempted_high': 0, 'attempted_traversal': 0, 'climb_time': None, 'final_climb_type': 'No Climb', 'defense_pct': 0, 'defense_rating': None, 'counter_defense_pct': 0, 'counter_defense_rating': None, 'driver_rating': None, 'auto_notes': 'notes for auto', 'teleop_notes': 'notes for teleop', 'misc_notes': 'notes for misc'}[0m
[32m2022-07-08 12:51:39.113 | DEBUG    |  [DataReader.py:77] Scanned Successfully![0m
[1;33m2022-07-08 12:51:39.450 | WARNING  |  [DataReader.py:79] Already Scanned[0m
[1;33m2022-07-08 12:51:39.715 | WARNING  |  [DataReader.py:79] Already Scanned[0m
[37m2022-07-08 12:51:42.115 | INFO     |  [DataReader.py:75] {'scout_id': 'varun', 'match_key': 'qm3', 'team_number': 2068, 'alliance': 'Red', 'driver_station': 3, 'preloaded_cargo': 1, 'auto_lower_hub': 0, 'auto_upper_hub': 2, 'auto_misses': 0, 'taxied': 1, 'auto_shooting_zones': None, 'teleop_lower_hub': 0, 'teleop_upper_hub': 3, 'teleop_misses': 4, 'teleop_shooting_zones': 'Elsewhere', 'attempted_low': 0, 'attempted_mid': 1, 'attempted_high': 0, 'attempted_traversal': 0, 'climb_time': 2, 'final_climb_type': 'Mid', 'defense_pct': 0, 'defense_rating': None, 'counter_defense_pct': 0, 'counter_defense_rating': 3, 'driver_rating': 4, 'auto_notes': 'notes for auto', 'teleop_notes': 'notes for teleop', 'misc_notes': 'notes for misc'}[0m
[32m2022-07-08 12:51:42.115 | DEBUG    |  [DataReader.py:77] Scanned Successfully![0m
[1;33m2022-07-08 12:51:43.911 | WARNING  |  [DataReader.py:79] Already Scanned[0m
[1;33m2022-07-08 12:51:44.246 | WARNING  |  [DataReader.py:79] Already Scanned[0m
[37m2022-07-08 12:51:47.849 | INFO     |  [DataManager.py:32] Validation succeeded for submission![0m
[37m2022-07-08 12:51:47.850 | INFO     |  [DataManager.py:32] Validation succeeded for submission![0m
[1;31m2022-07-08 12:51:47.850 | ERROR    |  [DataVal.py:315] In qm3, 3939 rated for counter defense but NO COUNTER DEFENSE PCT[0m
[1;31m2022-07-08 12:51:47.850 | ERROR    |  [DataVal.py:385] In qm3, 3939 INCORRECT TAXI according to TBA[0m
[37m2022-07-08 12:51:47.850 | INFO     |  [DataManager.py:32] Validation succeeded for submission![0m
[37m2022-07-08 12:51:47.850 | INFO     |  [DataManager.py:32] Validation succeeded for submission![0m
[1;31m2022-07-08 12:51:47.850 | ERROR    |  [DataVal.py:259] In qm3, 2068 MISSING AUTO SHOOTING ZONES[0m
[1;31m2022-07-08 12:51:47.850 | ERROR    |  [DataVal.py:315] In qm3, 2068 rated for counter defense but NO COUNTER DEFENSE PCT[0m
[1;31m2022-07-08 12:51:47.851 | ERROR    |  [DataVal.py:385] In qm3, 2068 INCORRECT TAXI according to TBA[0m
[1;31m2022-07-08 12:51:47.851 | ERROR    |  [DataVal.py:389] In qm3, 2068 INCORRECT ClIMB TYPE according to TBA[0m
[37m2022-07-08 12:51:47.851 | INFO     |  [DataManager.py:32] Validation succeeded for submission![0m
[37m2022-07-08 12:52:31.412 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 12:52:31.412 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 12:52:31.412 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 12:52:31.412 | INFO     |  [DataVal.py:562] Getting configuration variables from config.json[0m
[37m2022-07-08 12:52:31.412 | INFO     |  [DataVal.py:575] Successfully retreived configuration variablees.[0m
[37m2022-07-08 12:52:31.600 | INFO     |  [DataVal.py:603] Writing to match_schedule json.[0m
[37m2022-07-08 12:52:31.601 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 12:52:31.602 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 12:52:31.602 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 12:52:31.896 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 12:52:31.900 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 12:52:31.900 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 12:52:39.158 | INFO     |  [DataReader.py:75] {'scout_id': 'pranav', 'match_key': 'qm3', 'team_number': 1719, 'alliance': 'Red', 'driver_station': 2, 'preloaded_cargo': 1, 'auto_lower_hub': 0, 'auto_upper_hub': 0, 'auto_misses': 0, 'taxied': 1, 'auto_shooting_zones': 'Tarmac', 'teleop_lower_hub': 0, 'teleop_upper_hub': 1, 'teleop_misses': 5, 'teleop_shooting_zones': 'Elsewhere', 'attempted_low': None, 'attempted_mid': 1, 'attempted_high': None, 'attempted_traversal': None, 'climb_time': 1, 'final_climb_type': 'No Climb', 'defense_pct': 0, 'defense_rating': None, 'counter_defense_pct': 0, 'counter_defense_rating': None, 'driver_rating': None, 'auto_notes': 'notes for auto', 'teleop_notes': 'notes for teleop', 'misc_notes': 'notes for misc'}[0m
[32m2022-07-08 12:52:39.159 | DEBUG    |  [DataReader.py:77] Scanned Successfully![0m
[1;33m2022-07-08 12:52:39.721 | WARNING  |  [DataReader.py:79] Already Scanned[0m
[37m2022-07-08 12:52:40.321 | INFO     |  [DataReader.py:75] {'scout_id': 'paolo', 'match_key': 'qm3', 'team_number': 1908, 'alliance': 'Blue', 'driver_station': 1, 'preloaded_cargo': 1, 'auto_lower_hub': 0, 'auto_upper_hub': 0, 'auto_misses': 0, 'taxied': 1, 'auto_shooting_zones': 'Tarmac', 'teleop_lower_hub': 1, 'teleop_upper_hub': 2, 'teleop_misses': 0, 'teleop_shooting_zones': 'Fender;Opposing Tarmac', 'attempted_low': 0, 'attempted_mid': 1, 'attempted_high': 0, 'attempted_traversal': 0, 'climb_time': 1, 'final_climb_type': 'Mid', 'defense_pct': 0, 'defense_rating': None, 'counter_defense_pct': 0, 'counter_defense_rating': None, 'driver_rating': None, 'auto_notes': 'notes for auto', 'teleop_notes': 'notes for teleop', 'misc_notes': 'notes for misc'}[0m
[32m2022-07-08 12:52:40.321 | DEBUG    |  [DataReader.py:77] Scanned Successfully![0m
[1;33m2022-07-08 12:52:41.678 | WARNING  |  [DataReader.py:79] Already Scanned[0m
[1;33m2022-07-08 12:52:42.2 | WARNING  |  [DataReader.py:79] Already Scanned[0m
[37m2022-07-08 12:52:43.80 | INFO     |  [DataReader.py:75] {'scout_id': 'Samuel', 'match_key': 'qm3', 'team_number': 3939, 'alliance': 'Red', 'driver_station': 1, 'preloaded_cargo': 1, 'auto_lower_hub': 0, 'auto_upper_hub': 0, 'auto_misses': 0, 'taxied': None, 'auto_shooting_zones': None, 'teleop_lower_hub': 0, 'teleop_upper_hub': 1, 'teleop_misses': 3, 'teleop_shooting_zones': 'Tarmac;Launchpad;Terminal', 'attempted_low': 1, 'attempted_mid': None, 'attempted_high': None, 'attempted_traversal': None, 'climb_time': None, 'final_climb_type': 'No Climb', 'defense_pct': 0, 'defense_rating': None, 'counter_defense_pct': 0, 'counter_defense_rating': 3, 'driver_rating': 3, 'auto_notes': 'notes for auto', 'teleop_notes': 'notes for teleop', 'misc_notes': 'notes for misc'}[0m
[32m2022-07-08 12:52:43.81 | DEBUG    |  [DataReader.py:77] Scanned Successfully![0m
[1;33m2022-07-08 12:52:44.488 | WARNING  |  [DataReader.py:79] Already Scanned[0m
[1;33m2022-07-08 12:52:45.172 | WARNING  |  [DataReader.py:79] Already Scanned[0m
[37m2022-07-08 12:52:50.119 | INFO     |  [DataVal.py:87] Starting MATCH KEY VALIDATION qm3[0m
[37m2022-07-08 12:52:50.120 | INFO     |  [DataVal.py:89] Finished MATCH KEY VALIDATION qm3[0m
[37m2022-07-08 12:52:50.121 | INFO     |  [DataVal.py:95] Starting MATCH SCHEDULE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.121 | INFO     |  [DataVal.py:97] Finished MATCH SCHEDULE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.121 | INFO     |  [DataVal.py:102] Starting AUTO SCORE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.121 | INFO     |  [DataVal.py:104] Finished AUTO SCORE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.121 | INFO     |  [DataVal.py:106] Starting AUTO TAXI VALIDATION qm3[0m
[37m2022-07-08 12:52:50.121 | INFO     |  [DataVal.py:108] Finished AUTO TAXI VALIDATION qm3[0m
[37m2022-07-08 12:52:50.121 | INFO     |  [DataVal.py:110] Starting SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.121 | INFO     |  [DataVal.py:112] Finished SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.122 | INFO     |  [DataVal.py:114] Starting CLIMB VALIDATION qm3[0m
[37m2022-07-08 12:52:50.122 | INFO     |  [DataVal.py:116] Finished CLIMB VALIDATION qm3[0m
[37m2022-07-08 12:52:50.122 | INFO     |  [DataVal.py:118] Starting DEFENSE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.122 | INFO     |  [DataVal.py:120] Finished DEFENSE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.122 | INFO     |  [DataVal.py:130] Starting TBA VALIDATION qm3[0m
[37m2022-07-08 12:52:50.122 | INFO     |  [DataVal.py:132] Starting TBA VALIDATION qm3[0m
[37m2022-07-08 12:52:50.122 | INFO     |  [DataManager.py:32] Validation succeeded for submission![0m
[37m2022-07-08 12:52:50.123 | INFO     |  [DataVal.py:87] Starting MATCH KEY VALIDATION qm3[0m
[37m2022-07-08 12:52:50.123 | INFO     |  [DataVal.py:89] Finished MATCH KEY VALIDATION qm3[0m
[37m2022-07-08 12:52:50.123 | INFO     |  [DataVal.py:95] Starting MATCH SCHEDULE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.123 | INFO     |  [DataVal.py:97] Finished MATCH SCHEDULE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.123 | INFO     |  [DataVal.py:102] Starting AUTO SCORE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.123 | INFO     |  [DataVal.py:104] Finished AUTO SCORE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.123 | INFO     |  [DataVal.py:106] Starting AUTO TAXI VALIDATION qm3[0m
[37m2022-07-08 12:52:50.123 | INFO     |  [DataVal.py:108] Finished AUTO TAXI VALIDATION qm3[0m
[37m2022-07-08 12:52:50.123 | INFO     |  [DataVal.py:110] Starting SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.123 | INFO     |  [DataVal.py:112] Finished SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.123 | INFO     |  [DataVal.py:114] Starting CLIMB VALIDATION qm3[0m
[37m2022-07-08 12:52:50.123 | INFO     |  [DataVal.py:116] Finished CLIMB VALIDATION qm3[0m
[37m2022-07-08 12:52:50.123 | INFO     |  [DataVal.py:118] Starting DEFENSE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.124 | INFO     |  [DataVal.py:120] Finished DEFENSE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.124 | INFO     |  [DataVal.py:130] Starting TBA VALIDATION qm3[0m
[37m2022-07-08 12:52:50.124 | INFO     |  [DataVal.py:132] Starting TBA VALIDATION qm3[0m
[37m2022-07-08 12:52:50.124 | INFO     |  [DataManager.py:32] Validation succeeded for submission![0m
[37m2022-07-08 12:52:50.124 | INFO     |  [DataVal.py:87] Starting MATCH KEY VALIDATION qm3[0m
[37m2022-07-08 12:52:50.124 | INFO     |  [DataVal.py:89] Finished MATCH KEY VALIDATION qm3[0m
[37m2022-07-08 12:52:50.124 | INFO     |  [DataVal.py:95] Starting MATCH SCHEDULE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.124 | INFO     |  [DataVal.py:97] Finished MATCH SCHEDULE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.124 | INFO     |  [DataVal.py:102] Starting AUTO SCORE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.124 | INFO     |  [DataVal.py:104] Finished AUTO SCORE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.125 | INFO     |  [DataVal.py:106] Starting AUTO TAXI VALIDATION qm3[0m
[37m2022-07-08 12:52:50.125 | INFO     |  [DataVal.py:108] Finished AUTO TAXI VALIDATION qm3[0m
[37m2022-07-08 12:52:50.125 | INFO     |  [DataVal.py:110] Starting SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.126 | INFO     |  [DataVal.py:112] Finished SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.126 | INFO     |  [DataVal.py:114] Starting CLIMB VALIDATION qm3[0m
[37m2022-07-08 12:52:50.126 | INFO     |  [DataVal.py:116] Finished CLIMB VALIDATION qm3[0m
[37m2022-07-08 12:52:50.126 | INFO     |  [DataVal.py:118] Starting DEFENSE VALIDATION qm3[0m
[1;31m2022-07-08 12:52:50.127 | ERROR    |  [DataVal.py:315] In qm3, 3939 rated for counter defense but NO COUNTER DEFENSE PCT[0m
[37m2022-07-08 12:52:50.128 | INFO     |  [DataVal.py:120] Finished DEFENSE VALIDATION qm3[0m
[37m2022-07-08 12:52:50.128 | INFO     |  [DataVal.py:130] Starting TBA VALIDATION qm3[0m
[1;31m2022-07-08 12:52:50.128 | ERROR    |  [DataVal.py:385] In qm3, 3939 INCORRECT TAXI according to TBA[0m
[37m2022-07-08 12:52:50.128 | INFO     |  [DataVal.py:132] Starting TBA VALIDATION qm3[0m
[37m2022-07-08 12:52:50.128 | INFO     |  [DataManager.py:32] Validation succeeded for submission![0m
[37m2022-07-08 17:11:29.611 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:11:29.611 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:11:29.611 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:11:29.611 | INFO     |  [DataVal.py:562] Getting configuration variables from config.json[0m
[37m2022-07-08 17:11:29.611 | INFO     |  [DataVal.py:575] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:11:29.818 | INFO     |  [DataVal.py:603] Writing to match_schedule json.[0m
[37m2022-07-08 17:11:29.826 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:11:29.827 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:11:29.829 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:11:30.322 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:11:30.332 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:11:30.333 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:12:43.90 | INFO     |  [DataReader.py:75] {'scout_id': None, 'match_key': None, 'team_number': None, 'alliance': None, 'driver_station': None, 'preloaded_cargo': 0, 'auto_lower_hub': 0, 'auto_upper_hub': 0, 'auto_misses': None, 'taxied': None, 'auto_shooting_zones': None, 'teleop_lower_hub': None, 'teleop_upper_hub': None, 'teleop_misses': None, 'teleop_shooting_zones': None, 'attempted_low': None, 'attempted_mid': None, 'attempted_high': None, 'attempted_traversal': None, 'climb_time': None, 'final_climb_type': None, 'defense_pct': None, 'defense_rating': None, 'counter_defense_pct': None, 'counter_defense_rating': None, 'driver_rating': 3, 'auto_notes': None, 'teleop_notes': None, 'misc_notes': None}[0m
[32m2022-07-08 17:12:43.90 | DEBUG    |  [DataReader.py:77] Scanned Successfully![0m
[1;33m2022-07-08 17:12:43.494 | WARNING  |  [DataReader.py:79] Already Scanned[0m
[1;35m2022-07-08 17:12:50.785 | CRITICAL |  [DataManager.py:35] Validation failed.[0m
[37m2022-07-08 17:12:51.700 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:12:51.700 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:12:51.700 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:12:51.701 | INFO     |  [DataVal.py:562] Getting configuration variables from config.json[0m
[37m2022-07-08 17:12:51.701 | INFO     |  [DataVal.py:575] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:12:51.876 | INFO     |  [DataVal.py:603] Writing to match_schedule json.[0m
[37m2022-07-08 17:12:51.878 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:12:51.878 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:12:51.879 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:12:52.629 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:12:52.636 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:12:52.637 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:14:58.712 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:14:58.712 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:14:58.713 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:14:58.713 | INFO     |  [DataVal.py:563] Getting configuration variables from config.json[0m
[37m2022-07-08 17:14:58.713 | INFO     |  [DataVal.py:576] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:14:58.986 | INFO     |  [DataVal.py:604] Writing to match_schedule json.[0m
[37m2022-07-08 17:14:58.990 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:14:58.991 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:14:58.991 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:14:59.319 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:14:59.327 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:14:59.327 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:15:02.643 | INFO     |  [DataReader.py:77] {'scout_id': None, 'match_key': None, 'team_number': None, 'alliance': None, 'driver_station': None, 'preloaded_cargo': 0, 'auto_lower_hub': 0, 'auto_upper_hub': 0, 'auto_misses': None, 'taxied': None, 'auto_shooting_zones': None, 'teleop_lower_hub': None, 'teleop_upper_hub': None, 'teleop_misses': None, 'teleop_shooting_zones': None, 'attempted_low': None, 'attempted_mid': None, 'attempted_high': None, 'attempted_traversal': None, 'climb_time': None, 'final_climb_type': None, 'defense_pct': None, 'defense_rating': None, 'counter_defense_pct': None, 'counter_defense_rating': None, 'driver_rating': 3, 'auto_notes': None, 'teleop_notes': None, 'misc_notes': None}[0m
[32m2022-07-08 17:15:02.643 | DEBUG    |  [DataReader.py:79] Scanned Successfully![0m
[1;33m2022-07-08 17:15:02.839 | WARNING  |  [DataReader.py:81] Already Scanned[0m
[1;33m2022-07-08 17:15:02.975 | WARNING  |  [DataReader.py:81] Already Scanned[0m
[37m2022-07-08 17:16:32.866 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:16:32.867 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:16:32.867 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:16:32.867 | INFO     |  [DataVal.py:563] Getting configuration variables from config.json[0m
[37m2022-07-08 17:16:32.868 | INFO     |  [DataVal.py:576] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:16:33.136 | INFO     |  [DataVal.py:604] Writing to match_schedule json.[0m
[37m2022-07-08 17:16:33.142 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:16:33.143 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:16:33.143 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:16:33.503 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:16:33.511 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:16:33.512 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:18:42.316 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:18:42.317 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:18:42.317 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:18:42.317 | INFO     |  [DataVal.py:563] Getting configuration variables from config.json[0m
[37m2022-07-08 17:18:42.317 | INFO     |  [DataVal.py:576] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:18:42.586 | INFO     |  [DataVal.py:604] Writing to match_schedule json.[0m
[37m2022-07-08 17:18:42.590 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:18:42.591 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:18:42.591 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:18:42.878 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:18:42.885 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:18:42.885 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:19:01.370 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:19:01.372 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:19:01.372 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:19:01.372 | INFO     |  [DataVal.py:563] Getting configuration variables from config.json[0m
[37m2022-07-08 17:19:01.373 | INFO     |  [DataVal.py:576] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:19:02.964 | INFO     |  [DataVal.py:604] Writing to match_schedule json.[0m
[37m2022-07-08 17:19:02.968 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:19:02.969 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:19:02.969 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:19:04.598 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:19:04.605 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:19:04.606 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:21:58.981 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:21:58.982 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:21:58.983 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:21:58.983 | INFO     |  [DataVal.py:563] Getting configuration variables from config.json[0m
[37m2022-07-08 17:21:58.983 | INFO     |  [DataVal.py:576] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:21:59.164 | INFO     |  [DataVal.py:604] Writing to match_schedule json.[0m
[37m2022-07-08 17:21:59.168 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:21:59.169 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:21:59.169 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:21:59.495 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:21:59.502 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:21:59.502 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:22:22.374 | INFO     |  [DataReader.py:77] {'scout_id': 'S', 'match_key': 'c', 'team_number': 'o', 'alliance': 'u', 'driver_station': 't', 'preloaded_cargo': ' ', 'auto_lower_hub': 'I', 'auto_upper_hub': 'D', 'auto_misses': ',', 'taxied': 'M', 'auto_shooting_zones': 'a', 'teleop_lower_hub': 't', 'teleop_upper_hub': 'c', 'teleop_misses': 'h', 'teleop_shooting_zones': ' ', 'attempted_low': 'K', 'attempted_mid': 'e', 'attempted_high': 'y', 'attempted_traversal': ',', 'climb_time': 'T', 'final_climb_type': 'e', 'defense_pct': 'a', 'defense_rating': 'm', 'counter_defense_pct': ' ', 'counter_defense_rating': 'N', 'driver_rating': 'u', 'auto_notes': 'm', 'teleop_notes': 'b', 'misc_notes': 'e'}[0m
[32m2022-07-08 17:22:22.374 | DEBUG    |  [DataReader.py:79] Scanned Successfully![0m
[37m2022-07-08 17:22:25.873 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION c[0m
[37m2022-07-08 17:22:25.874 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION c[0m
[37m2022-07-08 17:22:25.874 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION c[0m
[1;31m2022-07-08 17:22:25.874 | ERROR    |  [DataVal.py:227] In c, o INVALID MATCH KEY [0m
[1;31m2022-07-08 17:22:25.874 | ERROR    |  [DataVal.py:231] In c, o MATCH KEY NOT FOUND in schedule [0m
[37m2022-07-08 17:22:25.874 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION c[0m
[37m2022-07-08 17:22:25.874 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION c[0m
[1;35m2022-07-08 17:22:25.874 | CRITICAL |  [DataManager.py:35] Validation failed.[0m
[37m2022-07-08 17:24:01.597 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:24:01.599 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:24:01.599 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:24:01.599 | INFO     |  [DataVal.py:563] Getting configuration variables from config.json[0m
[37m2022-07-08 17:24:01.599 | INFO     |  [DataVal.py:576] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:24:01.883 | INFO     |  [DataVal.py:604] Writing to match_schedule json.[0m
[37m2022-07-08 17:24:01.888 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:24:01.889 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:24:01.889 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:24:02.340 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:24:02.348 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:24:02.349 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:24:07.184 | INFO     |  [DataReader.py:77] {'scout_id': 'S', 'match_key': 'M', 'team_number': 'T', 'alliance': 'A', 'driver_station': 'D', 'preloaded_cargo': 'P', 'auto_lower_hub': 'A', 'auto_upper_hub': 'A', 'auto_misses': 'A', 'taxied': 'T', 'auto_shooting_zones': 'A', 'teleop_lower_hub': 'T', 'teleop_upper_hub': 'T', 'teleop_misses': 'T', 'teleop_shooting_zones': 'T', 'attempted_low': 'L', 'attempted_mid': 'M', 'attempted_high': 'H', 'attempted_traversal': 'T', 'climb_time': 'C', 'final_climb_type': 'F', 'defense_pct': 'H', 'defense_rating': 'D', 'counter_defense_pct': 'H', 'counter_defense_rating': 'C', 'driver_rating': 'D', 'auto_notes': ' ', 'teleop_notes': ' ', 'misc_notes': ' '}[0m
[32m2022-07-08 17:24:07.184 | DEBUG    |  [DataReader.py:79] Scanned Successfully![0m
[37m2022-07-08 17:24:21.82 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION M[0m
[37m2022-07-08 17:24:21.83 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION M[0m
[37m2022-07-08 17:24:21.84 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION M[0m
[1;31m2022-07-08 17:24:21.84 | ERROR    |  [DataVal.py:227] In M, T INVALID MATCH KEY [0m
[1;31m2022-07-08 17:24:21.84 | ERROR    |  [DataVal.py:231] In M, T MATCH KEY NOT FOUND in schedule [0m
[37m2022-07-08 17:24:21.84 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION M[0m
[37m2022-07-08 17:24:21.84 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION M[0m
[1;35m2022-07-08 17:24:21.84 | CRITICAL |  [DataManager.py:35] Validation failed.[0m
[37m2022-07-08 17:26:37.87 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:26:37.89 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:26:37.89 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:26:37.89 | INFO     |  [DataVal.py:563] Getting configuration variables from config.json[0m
[37m2022-07-08 17:26:37.90 | INFO     |  [DataVal.py:576] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:26:37.337 | INFO     |  [DataVal.py:604] Writing to match_schedule json.[0m
[37m2022-07-08 17:26:37.341 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:26:37.341 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:26:37.341 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:26:37.768 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:26:37.775 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:26:37.776 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:26:43.996 | INFO     |  [DataReader.py:76] {'scout_id': 'S', 'match_key': 'M', 'team_number': 'T', 'alliance': 'A', 'driver_station': 'D', 'preloaded_cargo': 'P', 'auto_lower_hub': 'A', 'auto_upper_hub': 'A', 'auto_misses': 'A', 'taxied': 'T', 'auto_shooting_zones': 'A', 'teleop_lower_hub': 'T', 'teleop_upper_hub': 'T', 'teleop_misses': 'T', 'teleop_shooting_zones': 'T', 'attempted_low': 'L', 'attempted_mid': 'M', 'attempted_high': 'H', 'attempted_traversal': 'T', 'climb_time': 'C', 'final_climb_type': 'F', 'defense_pct': 'H', 'defense_rating': 'D', 'counter_defense_pct': 'H', 'counter_defense_rating': 'C', 'driver_rating': 'D', 'auto_notes': ' ', 'teleop_notes': ' ', 'misc_notes': ' '}[0m
[32m2022-07-08 17:26:43.997 | DEBUG    |  [DataReader.py:78] Scanned Successfully![0m
[1;33m2022-07-08 17:26:44.263 | WARNING  |  [DataReader.py:80] Already Scanned[0m
[37m2022-07-08 17:27:27.432 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:27:27.433 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:27:27.433 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:27:27.433 | INFO     |  [DataVal.py:563] Getting configuration variables from config.json[0m
[37m2022-07-08 17:27:27.434 | INFO     |  [DataVal.py:576] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:27:27.653 | INFO     |  [DataVal.py:604] Writing to match_schedule json.[0m
[37m2022-07-08 17:27:27.658 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:27:27.658 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:27:27.659 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:27:27.879 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:27:27.886 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:27:27.887 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:27:29.792 | INFO     |  [DataReader.py:77] {'scout_id': 'S', 'match_key': 'M', 'team_number': 'T', 'alliance': 'A', 'driver_station': 'D', 'preloaded_cargo': 'P', 'auto_lower_hub': 'A', 'auto_upper_hub': 'A', 'auto_misses': 'A', 'taxied': 'T', 'auto_shooting_zones': 'A', 'teleop_lower_hub': 'T', 'teleop_upper_hub': 'T', 'teleop_misses': 'T', 'teleop_shooting_zones': 'T', 'attempted_low': 'L', 'attempted_mid': 'M', 'attempted_high': 'H', 'attempted_traversal': 'T', 'climb_time': 'C', 'final_climb_type': 'F', 'defense_pct': 'H', 'defense_rating': 'D', 'counter_defense_pct': 'H', 'counter_defense_rating': 'C', 'driver_rating': 'D', 'auto_notes': ' ', 'teleop_notes': ' ', 'misc_notes': ' '}[0m
[32m2022-07-08 17:27:29.792 | DEBUG    |  [DataReader.py:79] Scanned Successfully![0m
[37m2022-07-08 17:27:59.947 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:27:59.948 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:27:59.948 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:27:59.948 | INFO     |  [DataVal.py:563] Getting configuration variables from config.json[0m
[37m2022-07-08 17:27:59.949 | INFO     |  [DataVal.py:576] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:28:00.119 | INFO     |  [DataVal.py:604] Writing to match_schedule json.[0m
[37m2022-07-08 17:28:00.124 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:28:00.124 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:28:00.125 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:28:00.636 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:28:00.645 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:28:00.645 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:28:04.872 | INFO     |  [DataReader.py:77] {'scout_id': 'S', 'match_key': 'M', 'team_number': 'T', 'alliance': 'A', 'driver_station': 'D', 'preloaded_cargo': 'P', 'auto_lower_hub': 'A', 'auto_upper_hub': 'A', 'auto_misses': 'A', 'taxied': 'T', 'auto_shooting_zones': 'A', 'teleop_lower_hub': 'T', 'teleop_upper_hub': 'T', 'teleop_misses': 'T', 'teleop_shooting_zones': 'T', 'attempted_low': 'L', 'attempted_mid': 'M', 'attempted_high': 'H', 'attempted_traversal': 'T', 'climb_time': 'C', 'final_climb_type': 'F', 'defense_pct': 'H', 'defense_rating': 'D', 'counter_defense_pct': 'H', 'counter_defense_rating': 'C', 'driver_rating': 'D', 'auto_notes': ' ', 'teleop_notes': ' ', 'misc_notes': ' '}[0m
[32m2022-07-08 17:28:04.873 | DEBUG    |  [DataReader.py:79] Scanned Successfully![0m
[37m2022-07-08 17:29:30.667 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:29:30.668 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:29:30.668 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:29:30.668 | INFO     |  [DataVal.py:563] Getting configuration variables from config.json[0m
[37m2022-07-08 17:29:30.669 | INFO     |  [DataVal.py:576] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:29:30.868 | INFO     |  [DataVal.py:604] Writing to match_schedule json.[0m
[37m2022-07-08 17:29:30.871 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:29:30.872 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:29:30.873 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:29:31.287 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:29:31.294 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:29:31.294 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:30:32.896 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:30:32.897 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:30:32.897 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:30:32.898 | INFO     |  [DataVal.py:563] Getting configuration variables from config.json[0m
[37m2022-07-08 17:30:32.898 | INFO     |  [DataVal.py:576] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:30:33.189 | INFO     |  [DataVal.py:604] Writing to match_schedule json.[0m
[37m2022-07-08 17:30:33.193 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:30:33.194 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:30:33.194 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:30:33.828 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:30:33.836 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:30:33.836 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:32:00.336 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:32:00.337 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:32:00.337 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:32:00.337 | INFO     |  [DataVal.py:563] Getting configuration variables from config.json[0m
[37m2022-07-08 17:32:00.338 | INFO     |  [DataVal.py:576] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:32:00.561 | INFO     |  [DataVal.py:604] Writing to match_schedule json.[0m
[37m2022-07-08 17:32:00.565 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:32:00.565 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:32:00.566 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:32:01.45 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:32:01.52 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:32:01.53 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:32:27.651 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:32:27.653 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:32:27.653 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:32:27.653 | INFO     |  [DataVal.py:563] Getting configuration variables from config.json[0m
[37m2022-07-08 17:32:27.654 | INFO     |  [DataVal.py:576] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:32:27.818 | INFO     |  [DataVal.py:604] Writing to match_schedule json.[0m
[37m2022-07-08 17:32:27.822 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:32:27.823 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:32:27.823 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:32:27.995 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:32:28.2 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:32:28.2 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:32:31.715 | INFO     |  [DataReader.py:73] {'scout_id': 'sd', 'match_key': 'qm3', 'team_number': None, 'alliance': None, 'driver_station': None, 'preloaded_cargo': '1', 'auto_lower_hub': '0', 'auto_upper_hub': '0', 'auto_misses': '0', 'taxied': None, 'auto_shooting_zones': None, 'teleop_lower_hub': None, 'teleop_upper_hub': None, 'teleop_misses': None, 'teleop_shooting_zones': None, 'attempted_low': None, 'attempted_mid': None, 'attempted_high': '0', 'attempted_traversal': '0', 'climb_time': '0', 'final_climb_type': None, 'defense_pct': None, 'defense_rating': None, 'counter_defense_pct': None, 'counter_defense_rating': None, 'driver_rating': None, 'auto_notes': None, 'teleop_notes': None, 'misc_notes': None}[0m
[32m2022-07-08 17:32:31.715 | DEBUG    |  [DataReader.py:75] Scanned Successfully![0m
[37m2022-07-08 17:32:36.878 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm3[0m
[37m2022-07-08 17:32:36.879 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm3[0m
[37m2022-07-08 17:32:36.879 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm3[0m
[1;35m2022-07-08 17:32:36.879 | CRITICAL |  [DataManager.py:35] Validation failed.[0m
[37m2022-07-08 17:33:53.403 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:33:53.404 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:33:53.405 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:33:53.405 | INFO     |  [DataVal.py:563] Getting configuration variables from config.json[0m
[37m2022-07-08 17:33:53.406 | INFO     |  [DataVal.py:576] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:33:53.693 | INFO     |  [DataVal.py:604] Writing to match_schedule json.[0m
[37m2022-07-08 17:33:53.697 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:33:53.698 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:33:53.698 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:33:54.107 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:33:54.115 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:33:54.116 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:34:02.283 | INFO     |  [DataReader.py:73] {'scout_id': 'sd', 'match_key': 'qm3', 'team_number': '4099', 'alliance': None, 'driver_station': None, 'preloaded_cargo': '1', 'auto_lower_hub': '0', 'auto_upper_hub': '0', 'auto_misses': '0', 'taxied': None, 'auto_shooting_zones': None, 'teleop_lower_hub': None, 'teleop_upper_hub': None, 'teleop_misses': None, 'teleop_shooting_zones': None, 'attempted_low': None, 'attempted_mid': None, 'attempted_high': '0', 'attempted_traversal': '0', 'climb_time': '0', 'final_climb_type': None, 'defense_pct': None, 'defense_rating': None, 'counter_defense_pct': None, 'counter_defense_rating': None, 'driver_rating': None, 'auto_notes': None, 'teleop_notes': None, 'misc_notes': None}[0m
[32m2022-07-08 17:34:02.283 | DEBUG    |  [DataReader.py:75] Scanned Successfully![0m
[37m2022-07-08 17:34:07.605 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm3[0m
[37m2022-07-08 17:34:07.606 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm3[0m
[37m2022-07-08 17:34:07.606 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm3[0m
[1;35m2022-07-08 17:34:07.606 | CRITICAL |  [DataManager.py:35] Validation failed.[0m
[37m2022-07-08 17:36:08.459 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:36:08.459 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:36:08.459 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:36:08.460 | INFO     |  [DataVal.py:563] Getting configuration variables from config.json[0m
[37m2022-07-08 17:36:08.460 | INFO     |  [DataVal.py:576] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:36:09.143 | INFO     |  [DataVal.py:604] Writing to match_schedule json.[0m
[37m2022-07-08 17:36:09.146 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:36:09.148 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:36:09.148 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:36:09.570 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:36:09.575 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:36:09.576 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:36:19.549 | INFO     |  [DataReader.py:73] {'scout_id': 'sd', 'match_key': 'qm3', 'team_number': '4099', 'alliance': 'Blue', 'driver_station': 'on', 'preloaded_cargo': '1', 'auto_lower_hub': '3', 'auto_upper_hub': '4', 'auto_misses': '2', 'taxied': '1', 'auto_shooting_zones': None, 'teleop_lower_hub': None, 'teleop_upper_hub': '1', 'teleop_misses': None, 'teleop_shooting_zones': None, 'attempted_low': None, 'attempted_mid': None, 'attempted_high': '3', 'attempted_traversal': '2', 'climb_time': '2', 'final_climb_type': None, 'defense_pct': None, 'defense_rating': None, 'counter_defense_pct': None, 'counter_defense_rating': None, 'driver_rating': None, 'auto_notes': '1', 'teleop_notes': None, 'misc_notes': '1'}[0m
[32m2022-07-08 17:36:19.549 | DEBUG    |  [DataReader.py:75] Scanned Successfully![0m
[1;33m2022-07-08 17:36:20.49 | WARNING  |  [DataReader.py:77] Already Scanned[0m
[37m2022-07-08 17:36:24.802 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm3[0m
[37m2022-07-08 17:36:24.803 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm3[0m
[37m2022-07-08 17:36:24.803 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm3[0m
[1;31m2022-07-08 17:36:24.803 | ERROR    |  [DataVal.py:245] In qm3, frc4099 INCONSISTENT DRIVER STATION with schedule[0m
[37m2022-07-08 17:36:24.803 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm3[0m
[37m2022-07-08 17:36:24.803 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm3[0m
[1;33m2022-07-08 17:36:24.803 | WARNING  |  [DataVal.py:339] In qm3, 4099 shot 9 balls in Autonomous.[0m
[37m2022-07-08 17:36:24.803 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm3[0m
[37m2022-07-08 17:36:24.803 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm3[0m
[37m2022-07-08 17:36:24.804 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm3[0m
[37m2022-07-08 17:36:24.804 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm3[0m
[1;31m2022-07-08 17:36:24.804 | ERROR    |  [DataVal.py:260] In qm3, 4099 MISSING AUTO SHOOTING ZONES[0m
[1;35m2022-07-08 17:36:24.804 | CRITICAL |  [DataManager.py:35] Validation failed.[0m
[37m2022-07-08 17:37:47.795 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-08 17:37:47.795 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-08 17:37:47.795 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-08 17:37:47.796 | INFO     |  [DataVal.py:563] Getting configuration variables from config.json[0m
[37m2022-07-08 17:37:47.796 | INFO     |  [DataVal.py:576] Successfully retreived configuration variablees.[0m
[37m2022-07-08 17:37:48.87 | INFO     |  [DataVal.py:604] Writing to match_schedule json.[0m
[37m2022-07-08 17:37:48.90 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-08 17:37:48.90 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-08 17:37:48.91 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-08 17:37:48.614 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-08 17:37:48.618 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-08 17:37:48.618 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-08 17:37:55.99 | INFO     |  [DataReader.py:73] {'scout_id': 'paolo', 'match_key': 'qm3', 'team_number': '1908', 'alliance': 'Blue', 'driver_station': '1', 'preloaded_cargo': '1', 'auto_lower_hub': '0', 'auto_upper_hub': '0', 'auto_misses': '0', 'taxied': '1', 'auto_shooting_zones': 'Tarmac', 'teleop_lower_hub': '1', 'teleop_upper_hub': '2', 'teleop_misses': '0', 'teleop_shooting_zones': 'Fender;Opposing Tarmac', 'attempted_low': '0', 'attempted_mid': '1', 'attempted_high': '0', 'attempted_traversal': '0', 'climb_time': '1', 'final_climb_type': 'Mid', 'defense_pct': '0', 'defense_rating': None, 'counter_defense_pct': '0', 'counter_defense_rating': None, 'driver_rating': None, 'auto_notes': 'notes for auto', 'teleop_notes': 'notes for teleop', 'misc_notes': 'notes for misc'}[0m
[32m2022-07-08 17:37:55.99 | DEBUG    |  [DataReader.py:75] Scanned Successfully![0m
[1;33m2022-07-08 17:37:55.430 | WARNING  |  [DataReader.py:77] Already Scanned[0m
[37m2022-07-08 17:37:58.759 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm3[0m
[37m2022-07-08 17:37:58.759 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm3[0m
[37m2022-07-08 17:37:58.760 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm3[0m
[1;31m2022-07-08 17:37:58.760 | ERROR    |  [DataVal.py:245] In qm3, frc1908 INCONSISTENT DRIVER STATION with schedule[0m
[37m2022-07-08 17:37:58.760 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm3[0m
[37m2022-07-08 17:37:58.760 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm3[0m
[37m2022-07-08 17:37:58.760 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm3[0m
[37m2022-07-08 17:37:58.760 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm3[0m
[37m2022-07-08 17:37:58.760 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm3[0m
[37m2022-07-08 17:37:58.760 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-08 17:37:58.760 | INFO     |  [DataVal.py:113] Finished SHOOTING ZONE VALIDATION qm3[0m
[37m2022-07-08 17:37:58.761 | INFO     |  [DataVal.py:115] Starting CLIMB VALIDATION qm3[0m
[37m2022-07-08 17:37:58.761 | INFO     |  [DataVal.py:117] Finished CLIMB VALIDATION qm3[0m
[37m2022-07-08 17:37:58.761 | INFO     |  [DataVal.py:119] Starting DEFENSE VALIDATION qm3[0m
[37m2022-07-08 17:37:58.761 | INFO     |  [DataVal.py:121] Finished DEFENSE VALIDATION qm3[0m
[37m2022-07-08 17:37:58.761 | INFO     |  [DataVal.py:131] Starting TBA VALIDATION qm3[0m
[37m2022-07-08 17:37:58.761 | INFO     |  [DataVal.py:133] Starting TBA VALIDATION qm3[0m
[37m2022-07-08 17:37:58.761 | INFO     |  [DataManager.py:32] Validation succeeded for submission![0m
[37m2022-07-10 14:19:22.145 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-10 14:19:22.145 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[1;33m2022-07-10 14:19:22.146 | WARNING  |  [DataVal.py:27] Wifi Connection was not found. Will not check against TBA[0m
[37m2022-07-10 14:19:22.146 | INFO     |  [DataVal.py:613] Getting configuration variables from config.json[0m
[1;35m2022-07-10 14:19:22.146 | CRITICAL |  [DataVal.py:620] config.json not found. Make sure it's located in the data subdirectory.[0m
[37m2022-07-10 14:20:06.862 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-10 14:20:06.863 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[1;33m2022-07-10 14:20:06.863 | WARNING  |  [DataVal.py:27] Wifi Connection was not found. Will not check against TBA[0m
[37m2022-07-10 14:20:06.863 | INFO     |  [DataVal.py:613] Getting configuration variables from config.json[0m
[37m2022-07-10 14:20:06.863 | INFO     |  [DataVal.py:625] Successfully retreived configuration variablees.[0m
[37m2022-07-10 14:20:06.864 | INFO     |  [DataVal.py:633] Opening match_schedule_sheet.csv[0m
[37m2022-07-10 14:20:26.746 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-10 14:20:26.746 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[1;33m2022-07-10 14:20:26.746 | WARNING  |  [DataVal.py:27] Wifi Connection was not found. Will not check against TBA[0m
[37m2022-07-10 14:20:26.746 | INFO     |  [DataVal.py:613] Getting configuration variables from config.json[0m
[37m2022-07-10 14:20:26.747 | INFO     |  [DataVal.py:625] Successfully retreived configuration variablees.[0m
[37m2022-07-10 14:20:26.747 | INFO     |  [DataVal.py:633] Opening match_schedule_sheet.csv[0m
[37m2022-07-10 14:20:26.747 | INFO     |  [DataVal.py:640] Found match_schedule sheet. Converting to JSON object now[0m
[37m2022-07-10 14:20:26.747 | INFO     |  [DataVal.py:660] Posting data to match_schedule.json located in the data folder.[0m
[37m2022-07-10 14:20:48.532 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-10 14:20:48.533 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[1;33m2022-07-10 14:20:48.533 | WARNING  |  [DataVal.py:27] Wifi Connection was not found. Will not check against TBA[0m
[37m2022-07-10 14:20:48.533 | INFO     |  [DataVal.py:613] Getting configuration variables from config.json[0m
[37m2022-07-10 14:20:48.533 | INFO     |  [DataVal.py:625] Successfully retreived configuration variablees.[0m
[37m2022-07-10 14:20:48.534 | INFO     |  [DataVal.py:633] Opening match_schedule_sheet.csv[0m
[37m2022-07-10 14:20:48.534 | INFO     |  [DataVal.py:640] Found match_schedule sheet. Converting to JSON object now[0m
[37m2022-07-10 14:20:48.534 | INFO     |  [DataVal.py:660] Posting data to match_schedule.json located in the data folder.[0m
[37m2022-07-10 14:20:48.535 | INFO     |  [DataVal.py:664] Success![0m
[37m2022-07-10 14:20:48.535 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-10 14:20:48.535 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-10 14:20:48.536 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-10 14:20:48.536 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-10 14:21:41.346 | INFO     |  [DataReader.py:73] {'scout_id': 'saraansh', 'match_key': 'qm1', 'team_number': '4099', 'alliance': 'Blue', 'driver_station': '1', 'preloaded_cargo': '1', 'auto_lower_hub': '3', 'auto_upper_hub': '1', 'auto_misses': '2', 'taxied': '1', 'auto_shooting_zones': 'Fender;Tarmac;Terminal;Elsewhere', 'teleop_lower_hub': '1', 'teleop_upper_hub': '1', 'teleop_misses': '1', 'teleop_shooting_zones': 'Tarmac;Terminal;Elsewhere', 'attempted_low': '1', 'attempted_mid': None, 'attempted_high': '1', 'attempted_traversal': '1', 'climb_time': '9', 'final_climb_type': 'Traversal', 'defense_pct': '1.0', 'defense_rating': '5', 'counter_defense_pct': '0.0', 'counter_defense_rating': '0', 'driver_rating': '3', 'auto_notes': None, 'teleop_notes': None, 'misc_notes': None}[0m
[32m2022-07-10 14:21:41.346 | DEBUG    |  [DataReader.py:75] Scanned Successfully![0m
[1;33m2022-07-10 14:21:42.441 | WARNING  |  [DataReader.py:77] Already Scanned[0m
[1;33m2022-07-10 14:21:56.132 | WARNING  |  [DataReader.py:77] Already Scanned[0m
[37m2022-07-10 14:22:06.210 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm1[0m
[37m2022-07-10 14:22:06.210 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm1[0m
[37m2022-07-10 14:22:06.211 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm1[0m
[1;31m2022-07-10 14:22:06.211 | ERROR    |  [DataVal.py:238] frc4099 was NOT IN MATCH qm1, on the Blue alliance[0m
[37m2022-07-10 14:22:06.211 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm1[0m
[37m2022-07-10 14:22:06.211 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm1[0m
[37m2022-07-10 14:22:06.212 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm1[0m
[37m2022-07-10 14:22:06.212 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm1[0m
[37m2022-07-10 14:22:06.213 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm1[0m
[37m2022-07-10 14:22:06.213 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm1[0m
[37m2022-07-10 14:22:06.213 | INFO     |  [DataVal.py:113] Finished SHOOTING ZONE VALIDATION qm1[0m
[37m2022-07-10 14:22:06.213 | INFO     |  [DataVal.py:115] Starting CLIMB VALIDATION qm1[0m
[37m2022-07-10 14:22:06.214 | INFO     |  [DataVal.py:117] Finished CLIMB VALIDATION qm1[0m
[37m2022-07-10 14:22:06.214 | INFO     |  [DataVal.py:119] Starting DEFENSE VALIDATION qm1[0m
[1;31m2022-07-10 14:22:06.214 | ERROR    |  [DataVal.py:316] In qm1, 4099 rated for counter defense but NO COUNTER DEFENSE PCT[0m
[37m2022-07-10 14:22:06.214 | INFO     |  [DataVal.py:121] Finished DEFENSE VALIDATION qm1[0m
[37m2022-07-10 14:22:06.214 | INFO     |  [DataManager.py:36] Validation succeeded for submission![0m
[37m2022-07-10 14:26:50.412 | INFO     |  [DataVal.py:17] Logging started[0m
[37m2022-07-10 14:26:50.412 | INFO     |  [DataVal.py:20] Starting Validation Process[0m
[37m2022-07-10 14:26:50.413 | INFO     |  [DataVal.py:24] Wifi Connection Exists. Will cross check against TBA[0m
[37m2022-07-10 14:26:50.413 | INFO     |  [DataVal.py:34] Reading match schedule JSON[0m
[37m2022-07-10 14:26:50.413 | INFO     |  [DataVal.py:37] Success! JSON match schdeule has been read.[0m
[37m2022-07-10 14:26:50.414 | INFO     |  [DataVal.py:61] Requesting TBA data[0m
[37m2022-07-10 14:26:50.815 | INFO     |  [DataVal.py:66] TBA data successfully retrieved[0m
[37m2022-07-10 14:26:50.822 | INFO     |  [DataWriter.py:14] Getting configuration variables from config.json[0m
[37m2022-07-10 14:26:50.823 | INFO     |  [DataWriter.py:28] Successfully retrieved configuration variables.[0m
[37m2022-07-10 14:28:37.275 | INFO     |  [DataReader.py:73] {'scout_id': 'saraansh', 'match_key': 'qm1', 'team_number': '4099', 'alliance': 'Blue', 'driver_station': '1', 'preloaded_cargo': '1', 'auto_lower_hub': '2', 'auto_upper_hub': '1', 'auto_misses': '1', 'taxied': '1', 'auto_shooting_zones': 'Tarmac;Elsewhere', 'teleop_lower_hub': '2', 'teleop_upper_hub': '1', 'teleop_misses': '1', 'teleop_shooting_zones': 'Fender;Tarmac;Elsewhere', 'attempted_low': '1', 'attempted_mid': None, 'attempted_high': '1', 'attempted_traversal': '1', 'climb_time': '9', 'final_climb_type': 'No Climb', 'defense_pct': '1.0', 'defense_rating': '4', 'counter_defense_pct': '1.0', 'counter_defense_rating': '3', 'driver_rating': '3', 'auto_notes': None, 'teleop_notes': None, 'misc_notes': None}[0m
[32m2022-07-10 14:28:37.275 | DEBUG    |  [DataReader.py:75] Scanned Successfully![0m
[37m2022-07-10 14:28:42.80 | INFO     |  [DataVal.py:88] Starting MATCH KEY VALIDATION qm1[0m
[37m2022-07-10 14:28:42.81 | INFO     |  [DataVal.py:90] Finished MATCH KEY VALIDATION qm1[0m
[37m2022-07-10 14:28:42.81 | INFO     |  [DataVal.py:96] Starting MATCH SCHEDULE VALIDATION qm1[0m
[1;31m2022-07-10 14:28:42.82 | ERROR    |  [DataVal.py:231] In qm1, 4099 MATCH KEY NOT FOUND in schedule [0m
[37m2022-07-10 14:28:42.82 | INFO     |  [DataVal.py:98] Finished MATCH SCHEDULE VALIDATION qm1[0m
[37m2022-07-10 14:28:42.82 | INFO     |  [DataVal.py:103] Starting AUTO SCORE VALIDATION qm1[0m
[37m2022-07-10 14:28:42.82 | INFO     |  [DataVal.py:105] Finished AUTO SCORE VALIDATION qm1[0m
[37m2022-07-10 14:28:42.82 | INFO     |  [DataVal.py:107] Starting AUTO TAXI VALIDATION qm1[0m
[37m2022-07-10 14:28:42.83 | INFO     |  [DataVal.py:109] Finished AUTO TAXI VALIDATION qm1[0m
[37m2022-07-10 14:28:42.83 | INFO     |  [DataVal.py:111] Starting SHOOTING ZONE VALIDATION qm1[0m
[37m2022-07-10 14:28:42.83 | INFO     |  [DataVal.py:113] Finished SHOOTING ZONE VALIDATION qm1[0m
[37m2022-07-10 14:28:42.83 | INFO     |  [DataVal.py:115] Starting CLIMB VALIDATION qm1[0m
[37m2022-07-10 14:28:42.83 | INFO     |  [DataVal.py:117] Finished CLIMB VALIDATION qm1[0m
[37m2022-07-10 14:28:42.84 | INFO     |  [DataVal.py:119] Starting DEFENSE VALIDATION qm1[0m
[1;31m2022-07-10 14:28:42.84 | ERROR    |  [DataVal.py:324] In qm1, 4099 DEFENSE AND COUNTER DEFENSE PCT TOO HIGH[0m
[37m2022-07-10 14:28:42.84 | INFO     |  [DataVal.py:121] Finished DEFENSE VALIDATION qm1[0m
[37m2022-07-10 14:28:42.84 | INFO     |  [DataVal.py:131] Starting TBA VALIDATION qm1[0m
[37m2022-07-10 14:28:42.84 | INFO     |  [DataVal.py:133] Starting TBA VALIDATION qm1[0m
[37m2022-07-10 14:28:42.85 | INFO     |  [DataManager.py:36] Validation succeeded for submission![0m
